### ISSUE TITLE
How to donate ? plz!!!!!

### ISSUE THREAD

**Issue by jeanibarz** [HEnquist/camilladsp#105]
Hi,

Your work is great, and free. There is only one problem: I don't know how to donate :-1: 

Can you do something about it plz ? Thanks !

And continue the good work :+1: :1st_place_medal:

**Comment by HEnquist** [comment]
Hi!
Thank you! I don't expect any donations, I just do this because I enjoy it. But if you really really want to, you could use paypal. My email (gmail) is in my github profile.

**Comment by HEnquist** [comment]
That was really generous! Thank you so much :)
