### ISSUE TITLE
Problem with stdin->stdout pipe when format is not S16LE

### ISSUE THREAD

**Issue by mervinbeng** [HEnquist/camilladsp#113]
I've just started exploring camilladsp after having spent a few days reacquainting myself with brutefir. I uses brutefir with Logitech Media Server and squeezelite. It is working quite well and I was thinking of re-writing the DRC script for camllladsp.

In my first tests I've found that simple pipe-in pipe-out processing works, but only for S16LE to S16LE.

On linux: 
cat 16-bit.pcm | camilla 16-bit.config > 16-bit.raw # works fine.

If the config changes either stdin or stdout to S24LE, the output is bad - very clipped, not music.

Interesting observation: 16->24 gives a shorter output file (ratio 16:24); 24-16 gives a longer output file, 24->24 is correct size.

(The feature set and configuration possibilities of camilladsp look very good for use on a linux box!)

**Comment by HEnquist** [comment]
For which version did you see this? Is it specific for S24LE, or does it happen for other formats with >16 bits too?

**Comment by mervinbeng** [comment]
I used the latest Linux 64-bit x86 binary running on an up to date arch
kernel.

I'll look into other versions tomorrow.

Mervin

**Comment by HEnquist** [comment]
Ok! No need to try other camilladsp versions, but it would be great if you could test with some other sample formats.

**Comment by mervinbeng** [comment]
It seems to work with FLOAT32SE input to FLOAT32SE or to S16LE.

I would check on the S24LE input conversion. Processing and output seems
correct, it looks more like the S24LE input conversion is not correct.

**Comment by HEnquist** [comment]
Ok thanks! I'll look into it.

**Comment by HEnquist** [comment]
I have tried all formats both in and out, and they all work as expected.
Are you using the "right" 24-bit format? There are two, S24LE and S24LE3. The difference is that S24LE3 stores a sample as 3 bytes, while S24LE stores a sample as 4 bytes, where the actual data is in the lower 3 bytes and the highest one is zero-padding.

**Comment by mervinbeng** [comment]
Hi Henrik, you are correct, of course! I did not notice that the "S24LE"
used in camilladsp is what I usually think of as S24_32LE in Pulse, rather
than sox -b 24 or .s24 format. My bad!

Perhaps you could highlight that on the "Supported Formats" table? Seeing
the rows SE16LE, SE24LE then SE24LE3 probably gave me the impression that
it was sorted as 16, 24 and 32 bits. I know I should have checked closer.

<solved>

**Comment by HEnquist** [comment]
No worries! The 24-bit formats are often causing headaches. 
I added this in the FAQ:
https://github.com/HEnquist/camilladsp/commit/41159fbbd3a8ef45d3709d0087df1618ff0d2117
and a note in the readme:
https://github.com/HEnquist/camilladsp/commit/a92f1f29d512afdeafbb3f47ceea45931eb84622
