### ISSUE TITLE
Audio output stops working after song change in mpd

### ISSUE THREAD

**Issue by onodera-punpun** [HEnquist/camilladsp#116]
I am fairly sure this is a camilladsp problem? Setup is MacOS with BlackHole and then CamillaDSP for some audio-filters. Playing music through MPD, sometimes when the song changes, audio output stops till I restart camilladsp or change again to some other song. The good thing is that it always happens with the same songs, so in that way it is reproducible.

I think it might have something to do with different sample rates? In the following example I change from the working song to the not working song and back again (which fixes the output).

Song 1: `36 - 崖の上のポニョ (映画バージョン).flac: FLAC audio bitstream data, 16 bit, stereo, 44.1 kHz, 4248300 samples`
Song 2: `01 - ドライヴ.flac: FLAC audio bitstream data, 24 bit, stereo, 96 kHz, 22739334 samples`

Logs:

```
May 30 13:28:27.075 DEBG Opened CPAL playback device DAC01, module: camillalib::cpaldevice
May 30 13:28:27.075 DEBG Playback thread ready to start, module: camilladsp
May 30 13:28:27.075 TRCE Build f32 output stream, module: camillalib::cpaldevice
May 30 13:28:27.077 DEBG Opened CPAL capture device BlackHole 2ch, module: camillalib::cpaldevice
May 30 13:28:27.077 TRCE Build f32 input stream, module: camillalib::cpaldevice
May 30 13:28:27.077 DEBG Capture thread ready to start, module: camilladsp
May 30 13:28:27.077 DEBG Both capture and playback ready, release barrier, module: camilladsp
May 30 13:28:27.113 TRCE f32 input stream ready, module: camillalib::cpaldevice
May 30 13:28:27.236 TRCE f32 output stream ready, module: camillalib::cpaldevice
May 30 13:28:27.236 DEBG Starting playback loop, module: camillalib::cpaldevice
May 30 13:28:27.236 DEBG Starting capture loop, module: camillalib::cpaldevice
May 30 13:28:28.251 TRCE Measured sample rate is 44386.569176240984 Hz, module: camillalib::cpaldevice
May 30 13:28:29.273 TRCE Measured sample rate is 44101.11351709622 Hz, module: camillalib::cpaldevice
May 30 13:28:30.295 TRCE Measured sample rate is 44096.77390151384 Hz, module: camillalib::cpaldevice
May 30 13:28:31.316 TRCE Measured sample rate is 44097.705442803344 Hz, module: camillalib::cpaldevice
May 30 13:28:32.338 TRCE Measured sample rate is 44101.122495722615 Hz, module: camillalib::cpaldevice

# I change the song here

May 30 13:28:32.855 WARN Playback interrupted, no data available, module: camillalib::cpaldevice

# I change the song back

May 30 13:28:38.214 TRCE Measured sample rate is 3833.471527418081 Hz, module: camillalib::cpaldevice
May 30 13:28:38.215 INFO Restarting playback after buffer underrun, module: camillalib::cpaldevice
May 30 13:28:39.236 TRCE Measured sample rate is 44095.23287059874 Hz, module: camillalib::cpaldevice
May 30 13:28:40.258 TRCE Measured sample rate is 44107.404113434415 Hz, module: camillalib::cpaldevice
May 30 13:28:41.280 TRCE Measured sample rate is 44096.274008421475 Hz, module: camillalib::cpaldevice
May 30 13:28:42.301 TRCE Measured sample rate is 44103.06869927258 Hz, module: camillalib::cpaldevice
May 30 13:28:43.323 TRCE Measured sample rate is 44099.511020342616 Hz, module: camillalib::cpaldevice
May 30 13:28:44.344 TRCE Measured sample rate is 44104.138959949014 Hz, module: camillalib::cpaldevice
May 30 13:28:45.366 TRCE Measured sample rate is 44097.92124282349 Hz, module: camillalib::cpaldevice
May 30 13:28:46.388 TRCE Measured sample rate is 44097.17134683605 Hz, module: camillalib::cpaldevice
May 30 13:28:47.410 TRCE Measured sample rate is 44100.4642167007 Hz, module: camillalib::cpaldevice
May 30 13:28:48.431 TRCE Measured sample rate is 44100.313139042104 Hz, module: camillalib::cpaldevice
May 30 13:28:49.453 TRCE Measured sample rate is 44102.4499049917 Hz, module: camillalib::cpaldevice
May 30 13:28:50.475 TRCE Measured sample rate is 44099.352740989714 Hz, module: camillalib::cpaldevice
May 30 13:28:51.496 TRCE Measured sample rate is 44099.22687799018 Hz, module: camillalib::cpaldevice
May 30 13:28:52.518 TRCE Measured sample rate is 44097.64247275553 Hz, module: camillalib::cpaldevice
May 30 13:28:53.540 TRCE Measured sample rate is 44104.89811627085 Hz, module: camillalib::cpaldevice
May 30 13:28:54.561 TRCE Measured sample rate is 44096.667819480295 Hz, module: camillalib::cpaldevice
May 30 13:28:55.583 TRCE Measured sample rate is 44100.30774343058 Hz, module: camillalib::cpaldevice
May 30 13:28:56.605 TRCE Measured sample rate is 44100.16745799449 Hz, module: camillalib::cpaldevice
May 30 13:28:57.626 TRCE Measured sample rate is 44096.26861379827 Hz, module: camillalib::cpaldevice
May 30 13:28:58.648 TRCE Measured sample rate is 44107.015507841046 Hz, module: camillalib::cpaldevice
May 30 13:28:59.670 TRCE Measured sample rate is 44099.81135281893 Hz, module: camillalib::cpaldevice
May 30 13:29:00.691 TRCE Measured sample rate is 44096.72897411349 Hz, module: camillalib::cpaldevice
May 30 13:29:01.713 TRCE Measured sample rate is 44103.1874178947 Hz, module: camillalib::cpaldevice
May 30 13:29:02.735 TRCE Measured sample rate is 44099.38153074111 Hz, module: camillalib::cpaldevice
May 30 13:29:03.756 TRCE Measured sample rate is 44099.14953044017 Hz, module: camillalib::cpaldevice
May 30 13:29:04.778 TRCE Measured sample rate is 44096.29916896151 Hz, module: camillalib::cpaldevice
May 30 13:29:05.800 TRCE Measured sample rate is 44099.28622688021 Hz, module: camillalib::cpaldevice
May 30 13:29:06.821 TRCE Measured sample rate is 44102.54526569656 Hz, module: camillalib::cpaldevice
May 30 13:29:07.843 TRCE Measured sample rate is 44093.145348578364 Hz, module: camillalib::cpaldevice
May 30 13:29:08.865 TRCE Measured sample rate is 44110.18392255949 Hz, module: camillalib::cpaldevice
May 30 13:29:09.886 TRCE Measured sample rate is 44096.12114688964 Hz, module: camillalib::cpaldevice
May 30 13:29:10.908 TRCE Measured sample rate is 44098.26829684557 Hz, module: camillalib::cpaldevice
May 30 13:29:11.930 TRCE Measured sample rate is 44103.10824329536 Hz, module: camillalib::cpaldevice
May 30 13:29:12.952 TRCE Measured sample rate is 44095.73455263494 Hz, module: camillalib::cpaldevice
May 30 13:29:13.973 TRCE Measured sample rate is 44101.433685085954 Hz, module: camillalib::cpaldevice
May 30 13:29:14.995 TRCE Measured sample rate is 44101.046954508805 Hz, module: camillalib::cpaldevice
```

**Comment by HEnquist** [comment]
I think what happens here is that MPD changes the sample rate of the playback side of the Blackhole device, and this in turn changes the samplerate of the capture side that CamillaDSP is using. The problem then is that the CPAL library that I'm currently using doesn't have any way of notifying that the sample rate changed. Unless there is a way to prevent sample rate changes on the Blackhole device, then this can't be solved until I implement CoreAudio support without CPAL. This is something I'm planning to do to avoid this kind of limitations. No promises for when that will be ready though.

**Comment by Wang-Yue** [comment]
I notice the same as well and the proposal to migrate to CoreAudio is the right solution. 
I am the author of CoreAudio output plugins in a few open source media players (mpd and cmus), though I have no knowledge of rust. 
Feel free to reach out to me if you have questions. 


In addition, CamillaDSP should be able to listen to format changes in the BlackHole device, and allow output to a corresponding format to the output device. 
For instance, if I play a 44.1k audio or a 96k audio, Assuming the internal sample rate is 192kHz,  I'd expect CamillaDSP do this for me:
BlackHole in(44.1k) -> rubato upsample it to 192k ->  Camilla process it at 192k -> rubato downsample it to 44.1k -> Output to device in 44.1k. 
BlackHole in(96k) -> rubato upsample it to 192k ->  Camilla process it at 192k -> rubato downsample it to 96k -> Output to device in 96k. 


Even better, CamillaDSP could let the internal sample rate change according to the input device as well. We should allow users to specify the DSP internal sample rate for 44.1k and 48k multiples separately.  This would be useful if user only wants to up/downsamples to only integer multiples of a given sample rate.
Using the same @onodera-punpun  example, I'd expect CamillaDSP do this for me:
BlackHole in(44.1k) -> rubato upsample it to 176.4k ->  Camilla process it at 176.4k -> rubato downsample it to 44.1k -> Output to device in 44.1k. 
BlackHole in(96k) -> rubato upsample it to 192k ->  Camilla process it at 192k -> rubato downsample it to 96k -> Output to device in 96k.

**Comment by Wang-Yue** [comment]
I can confirm the pre-release resolve this issue. I verified the new CoreAudio output is able to play various format and sample rate in bit-perfectly. Nice job done. 

The following script will allow @onodera-punpun  to change sample rate of both loopback and output device automatically, based on the track being played.

```
import camilladsp, time
c = camilladsp.CamillaConnection("127.0.0.1", 1234)
c.connect()
while True:
  if c.get_state() == camilladsp.ProcessingState.INACTIVE:
    reason = c.get_stop_reason()
    if reason == camilladsp.StopReason.CAPTUREFORMATCHANGE:
      config = c.get_previous_config()
      config['devices']['samplerate'] = int(reason.data)
      c.set_config(config)
  time.sleep(1)
```


Ideally it is better to decouple the DSP `samplerate` from the system device properties. 
A separate issue is reported in https://github.com/HEnquist/camilladsp/issues/149.

**Comment by HEnquist** [comment]
Thanks for testing this on the pre-release!
The script could be made a bit more general by taking the logic from the example here: https://github.com/HEnquist/camilladsp/blob/master/testscripts/play_wav.py#L36
That changes only the capture samplerate, and configures resampling if needed. That means the pipeline with any FIR-filters etc can stay unchanged.

**Comment by Wang-Yue** [comment]
Thanks for the link. 
I use different files for different rate, and have $samplerate$ in my config, so no resample is needed. 
yeah, for people who only use one file, SRC needs to be enabled.

**Comment by Wang-Yue** [comment]
btw, I hope there could be a blocking api that wait for such event rather than query it every second. is it possible?

**Comment by HEnquist** [comment]
> btw, I hope there could be a blocking api that wait for such event rather than query it every second. is it possible?

There could be. The current design is just because I have chosen to keep the websocket interface as simple as possible. But having camilladsp send something when various events happen could be quite helpful for the gui for example. I haven't decided yet.

**Comment by Wang-Yue** [comment]
Thanks. I filed another bug to keep track of this: https://github.com/HEnquist/camilladsp/issues/155

**Comment by balbuze** [comment]
hello, I meet the same behaviour, but on debian buster arm based, volumio 3 for RPI. Of course this different but do you met this too?

**Comment by HEnquist** [comment]
> hello, I meet the same behaviour, but on debian buster arm based, volumio 3 for RPI. Of course this different but do you met this too? Probably not the same origin though. But mpd hangs in similar way. You can remove or move this post if unrelated

That is definitely a completely separate issue! The issue here is very macOS-specific.

**Comment by Wang-Yue** [comment]
> hello, I meet the same behaviour, but on debian buster arm based, volumio 3 for RPI. Of course this different but do you met this too? Probably not the same origin though. But mpd hangs in similar way. You can remove or move this post if unrelated

I tested this on my raspberry pi 4 and this issue does not appear with MPD. With alsa_cdsp you shouldn't experience it. If you do, probably you should file a bug to that project.

**Comment by HEnquist** [comment]
1.0.0 released!
