### ISSUE TITLE
replace soundflower by blackhole in the readme ?

### ISSUE THREAD

**Issue by phelluy** [HEnquist/camilladsp#126]
many thanks for your very nice software project CamillaDSP. In addition, it is written in Rust, which I like !

I have used your work for doing room equalization on my hifi system with a Mac Silicon
It worked very well.

I have written a guide at:

https://github.com/phelluy/room_eq_mac_m1

The (very tiny) contribution is a Python script for converting the filter's data provided by Room EQ Wizard into the CamillaDSP format. 

I would also suggest to use the BlackHole virtual sound card instead of SoundFlower.

Best wishes,

ph

**Comment by HEnquist** [comment]
Nice guide! And nice conversion script :)
I'll add a link in the readme.

I'm slowly rewriting the readme. The plan is to split out the wasapi/alsa/coreaudio etc specifics to separate files. I'm also rewriting the coreaudio backend to get rid of cpal. After that is done (when I will have a much better understanding of coreaudio) then I'll  write the new coreaudio-specific readme. The new readme will mention both soundflower and blackhole. Super short version is that Soundflower is ancient and only works on intel macs, while blackhole sometimes gives choppy sound (https://github.com/ExistentialAudio/BlackHole/issues/273). The 16-channel version of Blackhole works better.

**Comment by HEnquist** [comment]
Closed by version 0.6.0.
