### ISSUE TITLE
Audiolense wav filter as impulse reponse

### ISSUE THREAD

**Issue by Xombu** [HEnquist/camilladsp#141]
I cannot use directly the wav Filter I create with Audiolense in Camilla 0.6.3 and MoOde. The only way around is to convert 2 wav files L+R into raw L16SE. 
I red in this forum that it may be due to a different header, can you help?

**Comment by HEnquist** [comment]
Unfortunately that didn't work out, it doesn't seem like you can attach files to an issue via email. Can you try attaching them in the github web ui?

**Comment by Xombu** [comment]
Sure, however it seems that github web ui doesn't support wav format, so please rename the sent file as Test441.wav before using it...
[Test441 - Copie.pdf](https://github.com/HEnquist/camilladsp/files/7315161/Test441.-.Copie.pdf)

**Comment by HEnquist** [comment]
That file works fine in v0.6.3 when I try it here. What error message did you get (that also seems to have gotten lost from the mail)? Can you also attach your config gfle?

**Comment by Xombu** [comment]
Hi, please find attached the error message when I open the pipeline editor. How (actually where...) can I find the config gfle? My config is a standard MoOde config.
[Camilla DSP.pdf](https://github.com/HEnquist/camilladsp/files/7317859/Camilla.DSP.pdf)

**Comment by HEnquist** [comment]
Aha! I updated pycamilladsp-plot, but forgot to make a new release.
Please update to the new version here: https://github.com/HEnquist/pycamilladsp-plot/releases/tag/v0.6.2

**Comment by HEnquist** [comment]
Great that it works, and thanks for reporting back!
I do this for my own enjoyment so I don't ask for any donations. But if you really want to you can send something with paypal to my gmail (it's in my profile here on Github).
