### ISSUE TITLE
Compile error Linux 

### ISSUE THREAD

**Issue by geowal19** [HEnquist/camilladsp#142]
When compiling, this error occurs. Happens with master and 0.6.3.

System is VERSION="18.04.6 LTS (Bionic Beaver)", rustc 1.51.0 and cargo 1.51.0

`error[E0277]: [f64; 5] is not an iterator
  --> src/biquadcombo.rs:90:50
   |
90 |         for (n, ((f, q), g)) in f_all.iter().zip(q_all).zip(g_all).enumerate() {
   |                                                  ^^^^^
   |                                                  |
   |                                                  expected an implementor of trait IntoIterator
   |                                                  help: consider borrowing here: &q_all
   |
   = note: the trait bound [f64; 5]: IntoIterator is not satisfied
   = note: required because of the requirements on the impl of IntoIterator for [f64; 5]

error[E0599]: the method zip exists for struct Zip<std::slice::Iter<'_, f64>, [f64; 5]>, but its trait bounds were not satisfied
  --> src/biquadcombo.rs:90:57
   |
90 |           for (n, ((f, q), g)) in f_all.iter().zip(q_all).zip(g_all).enumerate() {
   |                                                           ^^^ method cannot be called on Zip<std::slice::Iter<'_, f64>, [f64; 5]> due to unsatisfied trait bounds
   |
   = note: the following trait bounds were not satisfied:
           [f64; 5]: Iterator
           which is required by Zip<std::slice::Iter<'_, f64>, [f64; 5]>: Iterator
           Zip<std::slice::Iter<'_, f64>, [f64; 5]>: Iterator
           which is required by &mut Zip<std::slice::Iter<'_, f64>, [f64; 5]>: Iterator

error: aborting due to 2 previous errors

Some errors have detailed explanations: E0277, E0599.
For more information about an error, try rustc --explain E0277.
error: could not compile camilladsp

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed`

**Comment by HEnquist** [comment]
Fixed in the upcoming version 1.0.0
