### ISSUE TITLE
Pi Zero 2

### ISSUE THREAD

**Issue by ElliottDyson** [HEnquist/camilladsp#144]
Hi I was just wondering if camilladsp was capable on running on the new pi zero 2s and if so, how many taps could be run per channel for 2 channels?

**Comment by HEnquist** [comment]
It should run fine. I would guess it's about half the speed of a Pi 4. The smallish ram won't be a problem.
There are some numbers here: https://github.com/HEnquist/camilladsp#system-requirements

**Comment by HEnquist** [comment]
Please reopen if there are problems!
