### ISSUE TITLE
Very poor audio quality, crackling

### ISSUE THREAD

**Issue by geowal19** [HEnquist/camilladsp#147]
First, I need to say thank you for this incredible project! I have a little problem, though. 

I'm using a Core 2 Duo machine with 1GB of RAM with a good WiFi connection running Debian server. My source is Shairplay which pipes into a loopback on device hw:2 channel 0. Thus the camilladsp source is hw:2,1 and output is an 8 channel sound card on hw:0.

I get severe crackling, distortions and tiny pauses in the music. I have tried removing camilladsp from the system and it works fine so is not the WiFi capability, shairplay or my output HW.

camilliadsp is very simply setup with 2 input channels mapped to the 8 output channels without any filters etc. I have tried all sample rates that do not crash, resmapling and some other combinations. My setup is attached, if you have any pointers, that would be amazing! Thank you.

`devices:
  adjust_period: 10
  capture:
    avoid_blocking_read: false
    channels: 2
    device: hw:2,1
    format: S16LE
    retry_on_error: false
    type: Alsa
  capture_samplerate: 0
  chunksize: 1024
  enable_rate_adjust: false
  enable_resampling: false
  playback:
    channels: 8
    device: hw:0
    format: S32LE
    type: Alsa
  queuelimit: 4
  rate_measure_interval: 1
  resampler_type: BalancedAsync
  samplerate: 48000
  silence_threshold: 0
  silence_timeout: 0
  stop_on_rate_change: false
  target_level: 0
filters: {}
mixers:
  Mapping:
    channels:
      in: 2
      out: 8
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
    - dest: 1
      mute: false
      sources:
      - channel: 1
        gain: 0
        inverted: false
        mute: false
    - dest: 2
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
    - dest: 3
      mute: false
      sources:
      - channel: 1
        gain: 0
        inverted: false
        mute: false
    - dest: 4
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
    - dest: 5
      mute: false
      sources:
      - channel: 1
        gain: 0
        inverted: false
        mute: false
    - dest: 6
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
    - dest: 7
      mute: false
      sources:
      - channel: 1
        gain: 0
        inverted: false
        mute: false
pipeline:
- name: Mapping
  type: Mixer
`

**Comment by HEnquist** [comment]
That config should work pretty well. You should enable rate_adjust since that will prevent some uderruns when using a loopback. But your problems seem much worse than that.
To look into this, I would need a log output from a run where there is trouble. Use the debug mode, -v.

**Comment by geowal19** [comment]
I have the system working on a USB input running at 48kSPS, the shairplay runs at 44.1 fixed. 

Setting the global sample rate to anything other than a multiple of 48k makes camilladsp crash.

Setting the global to 48kHz and enabling the the Resampling to anything other than a multiple of 48k causes camilladsp to crash.

I'm not sure if this is expected behavior.

**Comment by geowal19** [comment]
Sorry I can another USB based sound card input into the PC that I can set the sample rate on. 

The error log is attached for when I attempt to change the sample rate to 44.1kHz. It seems the sound card doesn't support it however I don't understand why the resampling wouldn't work.

Output for my sound card:

`Playing raw data '/dev/zero' : Unsigned 8 bit, Rate 8000 Hz, Mono
HW Params of device "hw:1":
--------------------
ACCESS:  MMAP_INTERLEAVED RW_INTERLEAVED
FORMAT:  U8 S16_LE S32_LE FLOAT_LE S24_3LE

SUBFORMAT:  STD
SAMPLE_BITS: [8 32]
FRAME_BITS: [8 256]
CHANNELS: [1 8]
RATE: [8000 192000]
PERIOD_TIME: (10 8192000]
PERIOD_SIZE: [2 65536]
PERIOD_BYTES: [64 131072]
PERIODS: [2 1024]
BUFFER_TIME: (166 16384000]
BUFFER_SIZE: [32 131072]
BUFFER_BYTES: [1024 131072]
TICK_TIME: ALL
--------------------
Hardware PCM card 1 'Creative X-Fi' device 0 subdevice 1
Its setup is:
  stream       : PLAYBACK
  access       : RW_INTERLEAVED
  format       : U8
  subformat    : STD
  channels     : 1
  rate         : 8000
  exact rate   : 8000 (8000/1)
  msbits       : 8
  buffer_size  : 4000
  period_size  : 1000
  period_time  : 125000
  tstamp_mode  : NONE
  tstamp_type  : MONOTONIC
  period_step  : 1
  avail_min    : 1000
  period_event : 0
  start_threshold  : 4000
  stop_threshold   : 4000
  silence_threshold: 0
  silence_size : 0
  boundary     : 9007199254740992000
  appl_ptr     : 0
  hw_ptr       : 0`

[dsp_err.log](https://github.com/HEnquist/camilladsp/files/7497427/dsp_err.log)

**Comment by HEnquist** [comment]
Ok, it manages to open the playback device fine at 44.1 kHz. The problem is that it fails to open the capture device at 44.1 kHz:
```
Nov 08 13:12:06.584 DEBG Capture: supported channels, min: 2, max: 2, list: [2], module: camillalib::alsadevice
Nov 08 13:12:06.584 DEBG Capture: setting channels to 2, module: camillalib::alsadevice
Nov 08 13:12:06.584 DEBG Capture: supported samplerates: Discrete([48000]), module: camillalib::alsadevice
Nov 08 13:12:06.584 DEBG Capture: setting rate to 44100, module: camillalib::alsadevice
Nov 08 13:12:06.584 ERRO Capture error: ALSA function 'snd_pcm_hw_params_set_rate' failed with error 'EINVAL: Invalid argument', module: camilladsp
```
On the third line here, we can se that the capture device only supports 48 kHz. This probably means that another application (I guess Shairplay) keeps the Loopback open at that rate. To change the rate of an Alsa loopback, both sides must be closed. Then the first application that opens either side of it decides the rate. Try starting CamillaDSP first, then shairplay. And since you are using a loopback, set `enable_rate_adjust: true`.
If you need resampling, then set `enable_resampling: true` and `resampler_type: Synchronous`. Set the `capture_samplerate` to a rate that the capture device supports, and the `samplerate` to one that the playback device supports. It won't automatically select rates to make it work.

**Comment by geowal19** [comment]
Thank you. I have got it working. The ordering of starting was critical, there's seems to be some strange behaviour with Shairplay. If Shairplay opens first, it locks the loopback to 48kHz which is the wrong sample rate for it. If camillaDSP is opened first at a system rate of 44.1kHz, then Shairplay works on 44.1kHz properly. 

Very strange! Many thank you for helping me get to the bottom of that, I will close this issue.
