### ISSUE TITLE
ALSA function 'snd_pcm_readi' failed with error 'EIO: I/O error'

### ISSUE THREAD

**Issue by shinelikethesun** [HEnquist/camilladsp#148]
I'm about to migrate my working setup from brutefir to camilladsp. When using Alsa "snd_aloop" module as capture device (hw:0,1) with module option "timer_source", camilladsp fails with the following messages:

INFO Capture device supports rate adjust, module: camillalib::alsadevice
WARN Capture failed with error: ALSA function 'snd_pcm_readi' failed with error 'EIO: I/O error', module: camillalib::alsadevice
ERRO Capture error: ALSA function 'snd_pcm_readi' failed with error 'EIO: I/O error', module: camilladsp

Without the timer_source module option it works flawless.

Attached you see my config, verbose output of camilladsp and snd_aloop parameters.

Great project btw. - Thank you :-)

[camilla-with_timer_source.txt](https://github.com/HEnquist/camilladsp/files/7504917/camilla-with_timer_source.txt)
[camilla-without_timer_source.txt](https://github.com/HEnquist/camilladsp/files/7504918/camilla-without_timer_source.txt)

[myconfig.txt](https://github.com/HEnquist/camilladsp/files/7504919/myconfig.txt)
[snd_aloop-parameters.txt](https://github.com/HEnquist/camilladsp/files/7505893/snd_aloop-parameters.txt)

**Comment by HEnquist** [comment]
Thanks for the detailed report! I take a look.

Could you try once with "retry_on_error" set to true?

**Comment by shinelikethesun** [comment]
Hi Henrik,

thank you for your quick response. 

I edited the config file like this:

 capture:
    type: Alsa
    channels: 2
    device: "hw:0,1"
    format: S16LE
    **retry_on_error: true**

which leads to repeating messages:

WARN Capture failed with error: ALSA function 'snd_pcm_readi' failed with error 'EIO: I/O error', will try again., module: camillalib::alsadevice
WARN Capture failed with error: ALSA function 'snd_pcm_readi' failed with error 'EIO: I/O error', will try again., module: camillalib::alsadevice
WARN Capture failed with error: ALSA function 'snd_pcm_readi' failed with error 'EIO: I/O error', will try again., module: camillalib::alsadevice
WARN Capture failed with error: ALSA function 'snd_pcm_readi' failed with error 'EIO: I/O error', will try again., module: camillalib::alsadevice

and so on. 

Another thing i tried (for fun) is to set **avoid_blocking_read: true** which produces this messages when timer_source is set:

 WARN Still not enough frames available: 0, need: 1024. Capture timed out, will try again, module: camillalib::alsadevice
WARN Still not enough frames available: 0, need: 1024. Capture timed out, will try again, module: camillalib::alsadevice
WARN Still not enough frames available: 0, need: 1024. Capture timed out, will try again, module: camillalib::alsadevice
WARN Still not enough frames available: 0, need: 1024. Capture timed out, will try again, module: camillalib::alsadevice
WARN Still not enough frames available: 0, need: 1024. Capture timed out, will try again, module: camillalib::alsadevice
WARN Still not enough frames available: 0, need: 1024. Capture timed out, will try again, module: camillalib::alsadevice

Without "timer_source" set and with "avoid_blocking_read: true" I get choppy playback and:

WARN Still not enough frames available: 1020, need: 1024. Capture timed out, will try again, module: camillalib::alsadevice
WARN Still not enough frames available: 1016, need: 1024. Capture timed out, will try again, module: camillalib::alsadevice
WARN Still not enough frames available: 1011, need: 1024. Capture timed out, will try again, module: camillalib::alsadevice
WARN Still not enough frames available: 1007, need: 1024. Capture timed out, will try again, module: camillalib::alsadevice
WARN Prepare playback after buffer underrun, module: camillalib::alsadevice
WARN Still not enough frames available: 1011, need: 1024. Capture timed out, will try again, module: camillalib::alsadevice
WARN Still not enough frames available: 1019, need: 1024. Capture timed out, will try again, module: camillalib::alsadevice

Maybe this is a hint?

**Comment by HEnquist** [comment]
I have played a bit with that timer source setting now and can't get it to work properly. If I set the timer source to a real card that is idle, and try to record from the loopback with arecord, then arecord fails after a couple of seconds with an I/O error.
If the card is playing something, then arecord gives lots of overrun errors, and the records much less data than it should.

I also tried with alsaloop. I was playing a wav file with `aplay` to Loopback, and then used `alsaloop` to loop from the Loopback, to a real soundcard.
Without configuring any timer source, it works fine. But with timer source set to the real card, I can't get any sound. Both `aplay` and `alsaloop` give overrun/underrun errors.

So this doesn't seem to work very well. I would suggest not using any timer source, and instead using the rate adjust feature of CamillaDSP (just rate adjust, no resampling). That will fine-tune the rate of the Loopback to keep it running in sync with the real card.

The avoid_blocking_read problem is a bit strange, it seems to always sleep too short. There may be a math bug in the calculation of the sleep time. I'll look into that. But normally you should not need to enable this, it's only intended to work around bugs in some drivers. The Loopback doesn't need it.

**Comment by shinelikethesun** [comment]
I think I have to clarify why I'm using the timer_source. 

In my setup with brutefir, when timer_source wasn't available, there was always a clock drift which leads to buffer overrun after a while. In brutefir there was no drift compensation available at all. So I really was happy when there was a change in the alsa loop module to bind the clock to the hardware device instead of jiffies. (https://patchwork.kernel.org/project/alsa-devel/cover/20191120115856.4125-1-andrew_gabbasov@mentor.com/) This leads to a working brutefir setup with alsa loopback to hardware output without any problem and no need for "manipulating" the clock via software.

**Comment by HEnquist** [comment]
That is what I thought, I just can't get it to work at all on my system.
Does it work on yours if you replace CamillaDSP with alsaloop? That's what I tried in my second test.

There seems to be a chicken-and-egg problem. The Loopback doesn't seem to give any data if the physical card it uses as timer source isn't playing anything. And the physical card won't get anything to play as long as the Loopback isn't give any data..

**Comment by shinelikethesun** [comment]
I edited my previous post (overlapped with your post) :-)

I really want to get camilladsp running with this setup.

I'll try out some things tomorrow with alsaloop. If you can give me some commands you've tried I will also try it on my setup. 

Maybe there is some dependency with the used hardware device. I'm using an RME UFX+ USB. I don't know....

The only thing I know is, that it is working with brutefir "rock-solid"

**Comment by HEnquist** [comment]
I can copy the commands I used tomorrow.

But don't worry about using rate adjust. It just affects the rate of the virtual clock of the Loopback device. This has no effect on the data passing through it, and won't cause any jitter in your physical card. And besides the rate will pretty quickly settle to a nearly constant value and then mainly vary slowly because of things like thermal drift.

**Comment by shinelikethesun** [comment]
Hi Henrik,

i tried some things with alsaloop, arecord and aplay this morning but with no success. My RME device needs S24_3LE as sample format but there seems to be some sort of problem (bug?!) which results in messages like:

Sample format not available for playback hw:1: Invalid argument
Unable to set parameters for playback hw:1 stream: Invalid argument

although it is set correctly (alsaloop -f S24_3LE -C hw:0,1 -P hw:1) - very frustrating

Thank you for clarifying the rate adjust thing.

It seems that brutefir is working with alsa devices in a different way. I attached a "stupid" config which only takes input from alsa loopback and outputs it to 6 channels without any filter. Would be interesting if this works on your setup - if you have the time to test it... :-)

[brutefir-working.txt](https://github.com/HEnquist/camilladsp/files/7519716/brutefir-working.txt)
[brutefir-log.txt](https://github.com/HEnquist/camilladsp/files/7519723/brutefir-log.txt)

**Comment by HEnquist** [comment]
I tried the brutefir config, and it works in my system to both with and without setting the timer source of the loopback.

With arecord|aplay I get the same error as you (with timer source set):
```
arecord -D hw:0,1 -r 44100 -f S16_LE -c 2| aplay -D hw:2 -r 44100 -f S16_LE -c 2 
Recording WAVE 'stdin' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
Playing WAVE 'stdin' : Signed 16 bit Little Endian, Rate 44100 Hz, Stereo
arecord: pcm_read:2211: read error: Input/output error
```

**Comment by HEnquist** [comment]
I'm guessing it works with brutefir because it happens to start the playback and capture devices in just the right way. I can't get it to work properly with any combination of aplay&arecord. This seems really flaky, I'm not very keen on spending time on making it work. Especially since CamillaDSP already solves the problem, just in a different way.

**Comment by shinelikethesun** [comment]
Yes! I understand...

Anyway - thank you for your time. :-)

**Comment by HEnquist** [comment]
Ok, closing!
