### ISSUE TITLE
Decouple internal sample rate with capture/playback device sample rate

### ISSUE THREAD

**Issue by Wang-Yue** [HEnquist/camilladsp#149]
For instance, if I play a 44.1k audio or a 96k audio, Assuming the internal sample rate is 176.4k or 192kHz, I'd expect CamillaDSP do this for me:
BlackHole in(44.1k) -> rubato upsample it to 176.4k -> Camilla process it at 176.4k -> rubato downsample it to 44.1k -> Output to device in 44.1k.
BlackHole in(96k) -> rubato upsample it to 192k -> Camilla process it at 192k -> rubato downsample it to 96k -> Output to device in 96k.

I can use a python script to listen to the websocket and change the internal sample rate if it gives `StopReason`. This requires extra script (which is ok but cumbersome). But the real problem is, it does not allow me to do the downsampling mentioned above.

the maximum sample rate is limited by the capture/playback device. it's better that this limitation can be decoupled. 

Usually for DSP, oversampling and doing it at a higher rate is desired for higher precision and lower artifacts.

**Comment by HEnquist** [comment]
Adding resampling support also on the playback side is on the list of things I'm considering to maybe add in the future. Considering most devices support high samplerates (96kHz or above) these days, it's not a very high priority. It will also take a large effort to implement, and will make the config file more complicated.

If your playback device can do 96 kHz, I assume it can also do 88.2 kHz. Why then do you want to resample back to 44.1 kHz in the first example? Staying within the same rate group (44.1 or 48k) makes sense, but I'd let the playback device run at as high a rate as possible within the group. 

There are many cases where doing the rate switching automatically inside CamillaDSP (without a custom python script) won't work. For example, if using an interface with ADAT, then the number of channels depends on the samplerate. This needs more config changes than simply updating the rates. Then both the devices section and the pipeline with mixers etc may need to change. There is also many different opinions on how to handle different rates. Using an external script is a bit cumbersome yes but it's the only way to support all cases and user preferences.

**Comment by Wang-Yue** [comment]
I agree that scripts enabled flexibility and I also agree that todays's audio interface allow very high sample rates. 
Right now I am listening my 44.1 CDs at 176.4 and have a lot of fun! 

There are a few reasons that changing back to a lower sample rate is sometimes desired. apart from some old interface where higher sample rate is not available, you also mentioned that some interface only allow more channels when sample rate is lower. So we'll have to playback in a lower sample rate to get more channels. In addition to that, user may prefer to use their DAC chip's own roll off filter to get rid of unwanted ultrasonics.

**Comment by HEnquist** [comment]
I have thought a little more about this and come to the conclusion that I will not implement it. It would make the playback backend much more complicated (and also take a lot of time to implement). I don't think the benefits are large enough to motivate that.
