### ISSUE TITLE
Add API to list device names

### ISSUE THREAD

**Issue by Wang-Yue** [HEnquist/camilladsp#153]
the `GetSupportedDeviceTypes` API can list all available output plugins. It would be better to expose device names as well. 
Currently, this has to be done in another program (cpal-listdevice). Since you already have access to platform native APIs, listing it in the main program is almost trivial. Doing so has a few benefits. The most notable one is user will be able to select a device from a list (in camilla gui for instance) rather than typing it / installing another program.

**Comment by HEnquist** [comment]
This is certainly useful! It has been on my list for a while already, I just didn't find the time to start yet.

**Comment by HEnquist** [comment]
done in 2.0
