### ISSUE TITLE
[CoreAudio] Add exclusive (hog) mode

### ISSUE THREAD

**Issue by Wang-Yue** [HEnquist/camilladsp#156]
your WASAPI output has exclusive mode. We can add the same thing to CoreAudio. It is called Hog mode in the CoreAudio universe. 

Adding the feature is easy and I have written this C++ example for your reference:
https://github.com/MusicPlayerDaemon/MPD/blob/master/src/output/plugins/OSXOutputPlugin.cxx#L482-L532

You just need to first GetPropertyData then SetPropertyData on key kAudioDevicePropertyHogMode. 
note: this API is a toggle, not a setter so you always need to query it first.

**Comment by HEnquist** [comment]
I made a PR to add support for this in coreaudio-rs: https://github.com/RustAudio/coreaudio-rs/pull/83

**Comment by HEnquist** [comment]
A bit untested, but there is a version here that should work: https://github.com/HEnquist/camilladsp/tree/hogmode

**Comment by Wang-Yue** [comment]
Verified the 1.0-pre2 works fine. 

possible improvement:
https://github.com/HEnquist/camilladsp/blob/next100/src/coreaudiodevice.rs#L97

you probably don't need this warning if `device_pid == camilla_pid`, or probably you can use another warning message when this happens. 

(this message appears when trying to reload a config)

**Comment by Wang-Yue** [comment]
While I was thinking about this --- probably the place where you should fix is when the program is in inactive/stop mode and is waiting for a new config(such as a capture/playback device unplugged or sample rate change), you need to close that device and release the hog mode.

**Comment by HEnquist** [comment]
Thanks for testing! The warning when already owning the device is a mistake, I'll fix that. And yes of course hog mode should be released when the playback thread exits and releases the device.

**Comment by HEnquist** [comment]
1.0.0 released!
