### ISSUE TITLE
camilladsp busy loop

### ISSUE THREAD

**Issue by Wang-Yue** [HEnquist/camilladsp#159]
I found a strange bug in camilladsp when working with multiple scripts. 

How to reproduce:

environment: 
macOS 12.0.1 on Intel mac. 
zsh with minimal config.
default Terminal.app
camilladsp is the 1.0-alpha1 version got from your release page.
camiilagui backend (I downloaded v0.8.0 from your release page)

1. create a script run.sh

```
python3 camillagui/main.py &
python3 monitor.py &
./camilladsp setting.yml --port 1234 --wait  &
```

Notice running the camiilagui backend is required to reproduce this bug. 
I don't know why it matters--- It gets killed automatically after closing the terminal at step 5

2. create a monitor.py as 

```
import camilladsp
import sys
import time

c = camilladsp.CamillaConnection("127.0.0.1", 1234)

retry = False
while True:
  try:
    if retry:
      c.connect()
    state = c.get_state()
    if state == camilladsp.ProcessingState.RUNNING:
      print(c.get_capture_signal_rms()[0]- c.get_playback_signal_rms()[0])
#      print(c.get_capture_signal_peak(), c.get_playback_signal_peak())
    if state == camilladsp.ProcessingState.INACTIVE:
      reason = c.get_stop_reason()
      if reason == camilladsp.StopReason.CAPTUREFORMATCHANGE:
        config = c.get_previous_config()
        rate = int(reason.data)
        config['devices']['samplerate'] = rate
        c.set_config(config)
        print("Successfully adjust to the new sample rate!")
    retry = False
  except ConnectionRefusedError as e:
    print("Can't connect to CamillaDSP, is it running? Error:", e)
    retry = True
  except camilladsp.CamillaError as e:
    print("CamillaDSP replied with error:", e)
    retry = True
  except IOError as e:
    print("Websocket is not connected:", e)
    retry = True
  time.sleep(1)
```

3. my demo file is a simple pass through.
```
---
devices:
  samplerate: 48000
  chunksize: 4096
  capture:
    type: CoreAudio
    device: "BlackHole 16ch"
    channels: 2
    format: FLOAT32LE
  playback:
    type: CoreAudio
    channels: 2
    device: "ADI-2 Pro" # whatever usb audio device you have
    format: FLOAT32LE
```

4. in terminal, call
```
./run.sh
```

5. Now here's the tricky part: First turn off the terminal by cmd+q, and then disconnect the USB cable of the audio interface. Here the order matters. You have to turn off Terminal.app before disconnecting USB cable

6. My camilladsp is busy looping. 

7. To make sure it's not caused by my script running mad, Now you can do 
```
killall Python
```
and you'll see the python script process is killed. camilladsp is still using 100% of CPU. 

I don't have the rust build/debug environment but here's the stack when it's looping:

<img width="849" alt="Screen Shot 2021-11-20 at 23 26 12" src="https://user-images.githubusercontent.com/889340/142729943-0f3f5bbe-cd4b-419c-8ab8-37ff20a98931.png">

So it's busy performing the `recv_timeout` here:
https://github.com/HEnquist/camilladsp/blob/724ad6d883361d8725bb860a286ef275fc8f397a/src/bin.rs#L270

**Comment by Wang-Yue** [comment]
I did want to try to provide a full log but once I add `--logfile camilladsp.log --loglevel trace` to the `run.sh` script, the bug does not appear at all.

**Comment by HEnquist** [comment]
There loop it seems to get stuck in lacks some error handling that it should have. I'll fix that for the next prerelease, and that should solve this bug.

**Comment by HEnquist** [comment]
Please try alpha2 to see if it fixes this bug!
https://github.com/HEnquist/camilladsp/releases/tag/v1.0.0-alpha2

**Comment by Wang-Yue** [comment]
The bug is resolved! Many thanks! You're getting closer and closer!

I filed a new bug https://github.com/HEnquist/camilladsp/issues/160

**Comment by HEnquist** [comment]
1.0.0 released!
