### ISSUE TITLE
Only one thread is used for audio processing

### ISSUE THREAD

**Issue by Wang-Yue** [HEnquist/camilladsp#161]
There's a limitation that only one thread is used for processing. 
On low power devices such as Raspberry Pi, the DSP engine quickly consumes 100% CPU usage when the pipeline is long /sample rate is high. 

It seems that there's no easy fix to this. this piece of code is very procedural:
https://github.com/HEnquist/camilladsp/blob/master/src/filters.rs#L498

**Comment by HEnquist** [comment]
This limitation will be really hard to get around. The pipeline config is very free, so the logic for figuring out what can be done in parallel would get really complicated. I have already spent some time thinking about ways to split the work in more threads, but have not come up with any design I like. I have put this on my list of things that I will maybe look into at some point, but it's not high priority at the moment.

**Comment by Wang-Yue** [comment]
Yes, the pipeline is very free. 

A possible solution is to compute a computation DAG (directed acyclic graph) based on the config file, where each edge is your filter (such as a biquad), and each vertex is a node in mixer (so 2x4 may have 4 node), or connection point of two filters ( such as a gain -> biquad case, just treat it as a 1x1 mixer). 
each edge then can run as a thread doing producer-consumer. each vertex can become lock-free (ring buffer) queues. a vertex is either 1xN or Nx1 so N queues is needed.
compared to your current program, the above program can perform on multiple threads lock free. the drawback is a lot of memcpy is needed, where your filtergroup is done in place, and much longer latency is expected. the latter can be optimized by merging various filters into filter groups. 

to achieve the above, the entire program needs to be refactored.

**Comment by HEnquist** [comment]
Yes something like that will be needed. Unfortunately the longer latency isn't really an acceptable tradeoff. And the (much!) increased complexity will invite all kinds of bugs.

For the time being, the processing will have to stay single threaded. I'm closing this issue since I'm not planning to do any work on it.
