### ISSUE TITLE
Waking up from sleep

### ISSUE THREAD

**Issue by abrombo** [HEnquist/camilladsp#168]
I am using camilladsp in an htpc.  When I am not watching the htpc (ubuntu 20.04) I put the computer into suspend/sleep mode.  If I have camilla running when I suspend the computer and then wake up the computer a (approximately) 12 second latency is introduced whenever I start an audio or video.  If after waking up the computer I kill and restart camilladsp there is no noticeable latency.  Any suggestions?  Note that I create the pulseaudio null sink in /etc/pulse/default.pa on boot.

**Comment by HEnquist** [comment]
I haven't seen this issue before. Can you post your camilla config file? Which camilladsp version are you running?
I have found that using an Alsa loopback device and configuring that as an alsa-sink in Pulse works better than using a null-sink. The pulse null-sink doesn't have any way to adjust its rate, so you need resampling to match the rates. With the alsa loopback you don't need that. Also reading from the null-sink uses more cpu than one would expect. I haven't figured out why, but there is no such problem with the alsa-sink and loopback.

**Comment by abrombo** [comment]
I have attached yml file.  I would like to use alsa for everything but I 
don't know how to route the audio from my apps to the alsa loopback 
device.  I downloaded your latest github source and compiled it for my 
hardware (Ryzen 5 3600 CPU, 6 cores/12 threads) using the instructions.  
Where do I learn how to configure an Alsa loopback device as an alsa 
sink in Pulse?

**Comment by HEnquist** [comment]
Unfortunately you can't upload files via email, only via the github web interface.

For setting it up with a loopback, check the example here: https://github.com/HEnquist/camilladsp-config
The alsa-sink is defined here: https://github.com/HEnquist/camilladsp-config/blob/master/default.pa#L44

That uses an Alsa "plug" to do format conversion. You can likely run without that, and point the alsa-sink directly to the loopback device.

**Comment by HEnquist** [comment]
Closing for now, please reopen (or open a new issue) if there are more questions!
