### ISSUE TITLE
pi4 alpine linux

### ISSUE THREAD

**Issue by csezoli21** [HEnquist/camilladsp#171]
Compatible with pi 4 alpine linux os?
Can t run.
Error:  No such file or directory.

**Comment by HEnquist** [comment]
Did you use the prebuilt binary? If you did, can you try compiling yourself? It's quite easy: https://github.com/HEnquist/camilladsp/blob/master/README.md#building

**Comment by csezoli21** [comment]
I tried both. I also built.

**Comment by HEnquist** [comment]
I'm guessing it's a glibc vs musl issue. Can you compile and run something else than camillladsp? Try creating a simple hello world example with cargo: https://doc.rust-lang.org/cargo/guide/creating-a-new-project.html

Unfortunately I'll have very little time to look into this the coming week or so.

**Comment by csezoli21** [comment]
Yes this works.

**Comment by HEnquist** [comment]
Ok, then the next step would be to figure out what file it tries and fails to open.

**Comment by csezoli21** [comment]
ok
