### ISSUE TITLE
Allow setting overlap-add as a percentage in FIR filter settings

### ISSUE THREAD

**Issue by soumyabanerjee** [HEnquist/camilladsp#192]
Since the convolution uses overlap add, would it be possible to expose the overlap as a percentage within the FIR filter settings with a default fallback to current ratio ?

**Comment by HEnquist** [comment]
As long as it's not using segmented convolution it's certainly possible. I can't say how it would affect things in segmented mode without looking at the math.
What would be the benefit? As it is now, a power-of-two chunksize gives a power-of-two FFT length for the convolution. This would no longer be the case if the overlap size is changed, and reducing the overlap to use a shorter but non-power-of-two length may end up being slower.

**Comment by soumyabanerjee** [comment]
Ah, didn't take in to account the partitioned convolution aspect. 
So the ask is purely from Window design standpoint - with certain custom Window functions I am getting less than ideal time domain performance since vast majority of the coefficients are nearer to 0, than say using Bartlett, Hann. The idea was to use a greater overlap. 
No worries, I think I will just convolve with Rectangular Window as a workaround.

**Comment by HEnquist** [comment]
I don't think I quite understand the problem. How long is your impulse response, and what chunksize do you want to run? Can you show an example of a problematic ir?

**Comment by HEnquist** [comment]
I have done some thinking about the segmented (ska partitioned) convolution. This becomes very complicated if the overlap is adjustable. And I believe anything that can be done with the adjustable overlap can also be done by suitable zero padding of the impulse response. In total I don't think adding this feature would be beneficial. I'll close this for now, but please reopen if you think of a good reason for doing that :)
