### ISSUE TITLE
Another issue with 24 LE

### ISSUE THREAD

**Issue by Foxenfurter** [HEnquist/camilladsp#194]
I am testing a pipeline for LMS and I want to be able to standardise to 24/96 before input into stdin for CamillaDSP and then output at 24/96 to stdout.

I have got this setup working at 44.1k and 16Bit but 96/24 eludes me. I have read the documentation and other posts, but there does not seem to be a post that explains this fully in one place - I am testing on Windows

here is my 44.1/16 command which works
flac -dcs --totally-silent break.flac | sox  -q -t wav - -t wav -C 0 -r 44100 -b16 - | camilladsp.exe sample.yml | sox  -q -t raw -b 16 -e signed -c 2 -r 44.1k -L - -t waveaudio 0

and my sample.yml
devices:
  samplerate: 44100
  buffersize: 1024
  silence_threshold: -60
  silence_timeout: 3.0
  capture:
    type: Stdin
    channels: 2
    format: S16LE
  playback:
    type: Stdout
    channels: 2
    format: S16LE
  
and here is my 24/96 which doesn't

flac -dcs --totally-silent break.flac | sox -q -t wav - -t wav -C 0 -r 96000 -b32 -L - | camilladsp.exe  Develop9624.yml  | sox  -q -t raw -b 24 -e signed -c 2 -r 96k -L - -t waveaudio 0

devices:
  samplerate: 96000
  buffersize: 2048
  silence_threshold: -60
  silence_timeout: 3.0

  enable_resampling: false
  enable_rate_adjust: false
  resampler_type: Synchronous 
  
  capture:
    type: Stdin
    channels: 2
    format: S24LE
  playback:
    type: Stdout
    channels: 2
    format: S24LE

I have tried multiple variations of the above with S24LE3 and S32LE with no luck. Any help greatly appreciated.

**Comment by HEnquist** [comment]
What error do you get? Garbage output?
I would suggest to start with 96k 16-bit on both capture and playback sides. That should work without issues. Then switch one side at a time to 24-bit to see where things fail.

**Comment by Foxenfurter** [comment]
Wow that was a quick response. I am getting white noise, I opened the files in audacity and it was clipped badly one channel worse than the other. Will try your suggestion and revert either way.

**Comment by Foxenfurter** [comment]
It is working now, thanks for the tip, I was a bit tired last night and going around in circles!  I have got something to move forward with. 

For future reference the conversion string looks like this.

flac -dcs --totally-silent break.flac | sox  -q -t wav - -t raw -C 0 -r 96000 -b24  - | camilladsp.exe Develop9624.yml | sox  -q -t raw -b 24 -e signed -c 2 -r 96k -L - -t waveaudio 0

where break.flac is 16bit @ 44.1k the last pipe into sox may be replaced and was just my way of checking playback from the command line on windows.

yml file looks like this i.e is using 24LE3 setting - 

devices:
  samplerate: 96000
  buffersize: 2048
  silence_threshold: -60
  silence_timeout: 3.0
  
  capture:
    type: Stdin
    channels: 2
    format: S24LE3
  playback:
    type: Stdout
    channels: 2
    format: S24LE3

**Comment by HEnquist** [comment]
Great that you got it working, and thanks for reporting back!
I'm planning to add an option to write a wav header to the output file, should make things like this a little easier.
