### ISSUE TITLE
Support HRTF?

### ISSUE THREAD

**Issue by Wang-Yue** [HEnquist/camilladsp#195]
It would be interesting if we could support HRTFs. There're various open source data set available. After matrix multiplication it should be possible to do the processing similar to how the existing convolution filter is working. 

With gyroscope sensor capturing realtime head movement data, a python script could adjust the parameters and simulate 3D space sound from a stereo or 7.1 source input. Could have some really interesting usage.

**Comment by siraaris** [comment]
I've wondered about this a bit also. Programs like BACCH (which I use in the entry level version without head tracking yet - so fixed listening position as such), takes input as distance between speakers and distance to listener to calculate the angle to listener).

I assume they have have generated a set of filters one for each angle, then use head tracking data to shift between points in a 3D matrix that they create from these filters.

BACCH also wants to be the last in DSP chain, as they adjust phase etc. 

I've wondered whether the HRTF for a specific position can be a generated as a filter using open source tools like 3D TuneIn, and then added into CamillaDSP as the last filter.

**Comment by HEnquist** [comment]
"Proper" HRTF with head tracking is a quite specialized application and not something I would like to add to camilladsp. But for fixed position, if the needed IRs can be exported from somewhere then it should be no problem to build a config to use them.

**Comment by HEnquist** [comment]
Closing for now, please reopen (or open a new issue) if there are more questions!
