### ISSUE TITLE
Loudness questions

### ISSUE THREAD

**Issue by ElliottDyson** [HEnquist/camilladsp#196]
Hi there. Should reference level be set to 75dB or 85dB? I presume the level that this is reached is set as the reference level. E.g. if it reaches 75/85dB at a volume of -8dB, that's what we set reference volume to be?

Also, how does the volume control work for this? Does it look at the volume directly through camillaDSP? Or can it see volume control elsewhere? I'm asking this point because I'm using moode Audio.

Thank you

**Comment by HEnquist** [comment]
There aren't any rules, just put the reference where it sounds good to you. Try setting the reference to the lowest gain you think that you want to use without any loudness correction. Then experiment with the settings until you are satisfied. My own preference is to have the correction only at quite low levels, when listening considerably below normal levels.

Presently it only uses the volume setting of camilladsp itself. I'm not very familiar with moOde so not sure if this is integrated somehow. Some future version may be able to read the volume setting from some Alsa mixer control.

**Comment by HEnquist** [comment]
Closing for now, please reopen (or open a new issue) if there are more questions!
