### ISSUE TITLE
use of unstable library feature 'proc_macro_is_available'

### ISSUE THREAD

**Issue by tmnvanderberg** [HEnquist/camilladsp#197]
While trying to build camilladsp on nixos the following error occurs:
```
error[E0658]: use of unstable library feature 'proc_macro_is_available'
  --> /home/tmn/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.37/src/detection.rs:28:21
   |
28 |     let available = proc_macro::is_available();
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: see issue #71436 <https://github.com/rust-lang/rust/issues/71436> for more information
   = help: add `#![feature(proc_macro_is_available)]` to the crate attributes to enable
```
From my limited understanding of the rust world, this means camilladsp now depends on a nightly compiler with unstable features enabled.

**Comment by HEnquist** [comment]
Yes that is what the error message means, but it's not supposed to require a nightly compiler. What branch did you build, and what rustc version did you use?

**Comment by HEnquist** [comment]
Closing for now, please reopen (or open a new issue) if there are more questions!
