### ISSUE TITLE
unclear document

### ISSUE THREAD

**Issue by Wang-Yue** [HEnquist/camilladsp#208]
camilladsp says:
` Async resampler not needed since capture device supports rate adjust. Switch to Sync type to save CPU time.`

doc says:
`When using the rate adjust feature to match capture and playback devices, one of the "Async" variants must be used. `

**Comment by Wang-Yue** [comment]
Also the warning message `Async resampler not needed since capture device supports rate adjust. Switch to Sync type to save CPU time.` cause confusion as well 1) the program is asking the user to switch. 2) the program switches by itself.

**Comment by pavhofman** [comment]
> Also the warning message `Async resampler not needed since capture device supports rate adjust. Switch to Sync type to save CPU time.` cause confusion as well 1) the program is asking the user to switch. 2) the program switches by itself.

I do not think CDSP switches by itself, the above is just a warning message https://github.com/HEnquist/camilladsp/blob/master/src/alsadevice.rs#L585

**Comment by pavhofman** [comment]
> doc says: `When using the rate adjust feature to match capture and playback devices, one of the "Async" variants must be used. `

That sentence is within a section about resamplers. But yeah, perhaps the resampling condition could be added, something like:

When using the rate adjust feature, which requires resampling to match capture and playback devices, one of the "Async" variants must be used.

**Comment by Wang-Yue** [comment]
Right, I understand what it does by reading the code. I just want to point out this sentence cause confusions.

**Comment by HEnquist** [comment]
I'll rephrase the log messages to make it clears they are only meant as suggestions for how the config could be improved.
