### ISSUE TITLE
Should the neon feature flag be removed?

### ISSUE THREAD

**Issue by t123yh** [HEnquist/camilladsp#209]
Hi,

Now that `rubato/neon` is not a flag anymore, may I ask if the `neon` feature flag serves any purpose? If not, should it be removed?

BTW, it seems that not only the resampler uses NEON, but also FIR filter will make use of it (from the RustFFT library). Is this a correct statement? If so, I think it should be added to the readme, as it currently only mentions only the resampler.

**Comment by HEnquist** [comment]
I was planning on keeping the neon feature flag to support the upcoming neon support of RustFFT. But don't think I'll do it that way. Instead I'll just enable the RustFFT neon support by default and bump the required rustc version to 1.61.
