### ISSUE TITLE
Synchronised audio output between multiple Pi's?

### ISSUE THREAD

**Issue by ElliottBridge** [HEnquist/camilladsp#210]
Hello, I was wondering if with the current camilladsp setup, it would be possible to have the DSP output in sync between multiple raspberry pis?
If the clocks between the processors were synced over the ethernet using NTP with one Master pi and multiple slave pis, would this work, or is the processing in CamillaDSP not time constant enough? If not would this be something that could be introduced for such situations?
This would both be useful for multiroom systems, and multichannel systems, either that are using CamillaDSP to run active speakers, or just with a large number of speakers, requiring outputs larger than the 8 channels supported by the raspberry pi and similar operating systems?

**Comment by pavhofman** [comment]
@ElliottBridge  I would recommend to talk to Charlie Laub (e.g. at diyaudio.com) who specialized in the synchronized streaming through RTP and gstreamer on the client side. The technology for the client still has a number of major caveats - e.g. no proper ASRC in gstreamer. CDSP has proper ASRC, but no RTP server nor client. Even if it did have RTP, aligning the RTP timestamps to the alsa sink presentation time is a MAJOR task, quite complicated.

**Comment by ElliottBridge** [comment]
> @ElliottBridge  I would recommend to talk to Charlie Laub (e.g. at diyaudio.com) who specialized in the synchronized streaming through RTP and gstreamer on the client side. The technology for the client still has a number of major caveats - e.g. no proper ASRC in gstreamer. CDSP has proper ASRC, but no RTP server nor client. Even if it did have RTP, aligning the RTP timestamps to the alsa sink presentation time is a MAJOR task, quite complicated.

I've just DMd him, I'll see what he suggests. Thank you

**Comment by ElliottBridge** [comment]
> @ElliottBridge  I would recommend to talk to Charlie Laub (e.g. at diyaudio.com) who specialized in the synchronized streaming through RTP and gstreamer on the client side. The technology for the client still has a number of major caveats - e.g. no proper ASRC in gstreamer. CDSP has proper ASRC, but no RTP server nor client. Even if it did have RTP, aligning the RTP timestamps to the alsa sink presentation time is a MAJOR task, quite complicated.

I've had a chat with him, and had a look at gstreamer. Doesn't really work for my needs, as each rapsberry pi would be fed different outputs, it's more the fact that the delay needs to be the same for the inputs and outputs on each of the raspberry pis. That's why I figured clock syncing the processors might work, but there's probably more than that, I'm not very confident in the technical details of audio processing pipelines. All I figured was that with synchronised clocks they'd process at the same speed as each other?

**Comment by HEnquist** [comment]
Closing this issue for now. This topic can be brought up again if I decide to add RTP support (which at the moment isn't very likely).
