### ISSUE TITLE
Support for Convolution using cuFFT

### ISSUE THREAD

**Issue by soumyabanerjee** [HEnquist/camilladsp#213]
Since CamillaDSP main convolution process isn't very good at distributing load in multi-core processors, would it instead be possible to offload the task to an Nvidia card using the cuFFT library ?
This is particularly helpful for very long FIR filters - 1M taps and above at 16FS rates. Will also cut down the latency if partitioned right I assume.

For smaller FIRs, CPU / SBC executed convolution is fine.

**Comment by HEnquist** [comment]
Just offloading the FFT isn't likely to be very helpful. Doing that will give a large overhead of moving small bits of data to and from the GPU. The way to do it would be to offload the entire convolution (FFT+multiplication with IR+iFFT). This is a big task, and currently not on my roadmap.

What is the use case for such long filters at such a high sample rate?

**Comment by soumyabanerjee** [comment]
> What is the use case for such long filters at such a high sample rate?

To design a reconstruction filter with extreme steepness at the highest supported PCM input sampling rate by a DAC.

**Comment by soumyabanerjee** [comment]
I understand this might be too esoteric a use-case. So fully understand why it's not in your current product roadmap.

**Comment by HEnquist** [comment]
> 
> To design a reconstruction filter with extreme steepness at the highest supported PCM input sampling rate by a DAC.

Ok I see, I was guessing something along those lines. I don't think there are that many who would be interested in using this, and for everyone else the convolution on the CPU is more than fast enough. I'll close this issue for now. Maybe I'll come back to it at some point, we'll see.
