### ISSUE TITLE
Another issue with camilladsp raspberry pi

### ISSUE THREAD

**Issue by ElliottBridge** [HEnquist/camilladsp#214]
Not sure if a GUI or DSP issue, so figured I'd put it here. After the last troubleshooting about setting CamillaDSP to a non graphical target, it had been working fairly well. But when left alone for several hours the gui seems to forget current configuration and sometimes loses full communication with camillaDSP saying it is no longer active. (when checking with systemctl, it says it's active). I'm now getting an issue where on reboot CamillaDSP says it's active (systemctl), but only gets recognised as being active by camillaGUI after the service has been restarted manually. As I said, no idea if it is a GUI or DSP issue. Sorry for all these issues, but if I'm getting them, I'm sure others are as well, my system is extremely stock, just Raspi lite 64bit and CamillaDSP, so not some kind of rare compatibility issue.

**Comment by ElliottBridge** [comment]
To add more detail. Rather than just using the active_config.yml file, if I have one inside the configs folder so that camillaGUI can see it, it seems to work without forcing a systemctl update, but forgets all the filters resulting in a broken pipe. (it remembers the mixer), if I force load the config through the GUI it fixes this. But seemingly only temporarily, eventually, maybe 1hr to 4hrs after forcing the config to be loaded through the GUI. Essentially, after a seemingly random amount of time, it resorts back to the original state where it has forgotten the filters.

**Comment by HEnquist** [comment]
My computer is packed up in a moving box so can't do very much at the moment unfortunately. I'll take a look as soon as I can after I have my things in order again!

When it forgets the config, does the camilladsp process exit and get restarted by systemd?

**Comment by ElliottBridge** [comment]
> My computer is packed up in a moving box so can't do very much at the moment unfortunately. I'll take a look as soon as I can after I have my things in order again!
> 
> When it forgets the config, does the camilladsp process exit and get restarted by systemd?

That's alright, thanks for getting back to me anyways. I don't believe this is what is happening, but to check I'll disable to autorestart type option in the .service file and see how it behaves. I'll get back to you with the notes on that tomorrow.

**Comment by ElliottBridge** [comment]
> My computer is packed up in a moving box so can't do very much at the moment unfortunately. I'll take a look as soon as I can after I have my things in order again!
> 
> When it forgets the config, does the camilladsp process exit and get restarted by systemd?

I set restart=never in camilladsp.service, it ran for a couple of hours then it became inactive, so it does indeed seem as though it was just closing down and restarting the service. No idea why though, and why when it does so it forgets the filters.

**Comment by HEnquist** [comment]
Sorry for not coming back, have been busy moving to a new apartment.
Let's start by figuring out why camilladsp exits. There should be an error in the log when it happens. Can you try to get the log out? Try something like `systemctl -l -n100 status camilladsp` after it has stopped. That should print the last 100 log messages (but I'm on a windows machine at the moment so can't try that it actually works).

**Comment by HEnquist** [comment]
Any update on this?

**Comment by HEnquist** [comment]
Closing, please reopen if it happens again.
