### ISSUE TITLE
32 channel option with pulse audio?

### ISSUE THREAD

**Issue by ElliottBridge** [HEnquist/camilladsp#215]
Imagine outputting up to 32 channels on one device through joining multiple high channel number sound cards in pulse audio? I know that part is possible, but how about a future update to camillaDSP that lets you process each of the 32 channels separately?!?!?!
Just an idea that I think would be pretty awesome, not sure how difficult it is to implement though... (Or pipewire, pipewire might be better)

**Comment by HEnquist** [comment]
There are several ways to make aggregate devices. It's supported by for example Alsa, Pipewire and CoreAudio. Not sure about Pulse. 
These all have in common that the audio api itself handles the aggregation, and presents a single virtual device that camilladsp (or any other application) can use. Camilladsp doesn't support outputting to several devices itself, and this is not something I'm planning on implementing.
The synchronization between the devices is usually not great, and this really limits how useful these aggregate devices are.

**Comment by ElliottBridge** [comment]
> There are several ways to make aggregate devices. It's supported by for example Alsa, Pipewire and CoreAudio. Not sure about Pulse. 
> These all have in common that the audio api itself handles the aggregation, and presents a single virtual device that camilladsp (or any other application) can use. Camilladsp doesn't support outputting to several devices itself, and this is not something I'm planning on implementing.
> The synchronization between the devices is usually not great, and this really limits how useful these aggregate devices are. 

I wasn't aware of poor synchronisation, but the plan wasn't for multidevice to be done within camillaDSP, more that all of those APIs support generating a virtual device of up to 32 channels in and out. It would then be that device that is used in camillaDSP. But until synchronisation is fixed, there's probably no point doing that. Pipewire is really new, is synchronisation just as bad with that?

**Comment by HEnquist** [comment]
I haven't tried this in Pipewire, so don't know how well it manages to sync. I know CoreAudio drifts too much for crossover duty. The Alsa multi plugin doesn't try syncing at all, but you can work around that by going via another loopback. Then you use the alsaloop tool to sync to each device. 
I haven't mentioned any of this in the READMEs since it's not an approach I would recommend using. I also haven't spent much time looking at it. But there are often questions about it so I should write something.

**Comment by siraaris** [comment]
Hi guys, I hope you don't mind me jumping in with a comment. 

Given the number of questions on the forum on this topic I think it would be good to write something that outlines a working approach.

The community will then start supporting each other :)

I'm happy to help!

**Comment by ElliottBridge** [comment]
> Hi guys, I hope you don't mind me jumping in with a comment. 
> 
> Given the number of questions on the forum on this topic I think it would be good to write something that outlines a working approach.
> 
> The community will then start supporting each other :)
> 
> I'm happy to help!

I think that would be an amazing idea. Didn't know there was a forum about this, didn't know this were many questions about this topic in particular either, but it makes sense. Getting lots of channels for DSP is pro audio stuff, and that is ridiculously expensive. Finding out a way to do powerful processing for many channels for less than £200 would be flippin' amazing. We've already got it up to 8 channels, but why stop there, there are tons of awesome projects you can do that are channel limited due to cost

**Comment by ElliottBridge** [comment]
> I haven't tried this in Pipewire, so don't know how well it manages to sync. I know CoreAudio drifts too much for crossover duty. The Alsa multi plugin doesn't try syncing at all, but you can work around that by going via another loopback. Then you use the alsaloop tool to sync to each device. 
> I haven't mentioned any of this in the READMEs since it's not an approach I would recommend using. I also haven't spent much time looking at it. But there are often questions about it so I should write something.

So is what you are saying, is that you can sync it up by utilising a loopback, with the downside being added delay?

**Comment by HEnquist** [comment]
> 
> So is what you are saying, is that you can sync it up by utilising a loopback, with the downside being added delay?

Yes, added delay and added complexity. I don't know how well it manages to sync, that will need some measurements.
Here is a little sketch:
```
                                                  -> loopback -> alsaloop -> device1
app -> loopback -> camilladsp -> alsa multi pcm -|
                                                  -> loopback -> alsaloop -> device2

**Comment by ElliottBridge** [comment]
> > 
> > So is what you are saying, is that you can sync it up by utilising a loopback, with the downside being added delay?
> 
> Yes, added delay and added complexity. I don't know how well it manages to sync, that will need some measurements.
> Here is a little sketch:
> ```
>                                                   -> loopback -> alsaloop -> device1
> app -> loopback -> camilladsp -> alsa multi pcm -|
>                                                   -> loopback -> alsaloop -> device2
> 

Great stuff. Ignoring all of the actual routing of audio, how many channels of audio can camillaDSP process separately to each other? My main question initially (which I don't think I communicated to well) was just this. Is camillaDSP itself limited to 8 channels or if we sent a virtual device like loopback into camillaDSP with more than 8 channels, can it handle it, and if so, how many?

**Comment by HEnquist** [comment]
Ah I completely misunderstood the question then:)

There is no limit on the number of channels. As long as you have processing power for all the filters you can have as many as you want.

**Comment by ElliottBridge** [comment]
> Well, I use 32 channels with each channel running the Gain, FIR and Volume filters, and the compressor across 24 of those channels. On CoreAudio on a Mac mini M1. 
> 
> No problem at all. 

May I ask what you use as a soundcard?

**Comment by siraaris** [comment]
I use a RME M-32 DA Pro. Primarily for development of active speakers. 

I’m looking at other options for production as RME don’t support Linux and to deduce overall cost of the loudspeaker.

Aris 

-- 
Aris Theocharides
M: +61 488 044 202

**Comment by HEnquist** [comment]
Should we close this issue?

**Comment by HEnquist** [comment]
Closing, feel free to reopen if needed.

**Comment by larryqiann** [comment]
I have the opposite question about this, actually. I'd like to use multiple inputs, for example, so that I can *mix* simultaneously playing audio in CamillaDSP from the Raspberry Pi itself and from an external ADC. I'm guessing that for this purpose, the drift is not so important, since the two sources are being mixed in software and the two channels are from the same source relative to each other. 

I'm wondering if anyone has experience setting this up in ALSA. I'm trying to figure out how to get it working, but having some difficulties and not sure where to ask for more help. If anyone knows where I might be able to find support with that, that would be greatly appreciated!
