### ISSUE TITLE
Switching between internal and external sound source

### ISSUE THREAD

**Issue by abrombo** [HEnquist/camilladsp#217]
I can make camilladsp work for an internal sound source (Ubuntu 20.04 pcie 7.1 sound card), that is a program running on the computer that produces the digital sound stream.  My question is can I use the usual loopback device to switch to an external sound source.  In my case the external source is the audio toslink from a Samsung smart tv when the tv is used to play Amazon Prime Videos to the optical input of the sound card.  Can the switching be done with scripts?  Since you use the loopback device for Camilla, can there be another loopdevice to do what I want to do?

PS: Camilladsp is a great program!

**Comment by HEnquist** [comment]
There are two ways you could to this. Either you make a separate camilladsp config where you make it capture from the spdif input, and switch to that config when you want the tv sound.
The other way is to leave camilladsp running with the same config, and use alsaloop to capture sound from the spdif input and send it to the same loopback as your usual playback software outputs to. This means you have to close the other program to make it release the loopback before you can switch (and to close alsaloop before you can switch back).
http://manpages.ubuntu.com/manpages/bionic/man1/alsaloop.1.html
