### ISSUE TITLE
Feature request: tilt as parametric eq

### ISSUE THREAD

**Issue by blbeczech82** [HEnquist/camilladsp#219]
Thank you for great job!
Would it be possible to add "tilt" parametric eq function?

Thank you...

**Comment by HEnquist** [comment]
Yes it would be possible, but in a way it already exists. You can use a high or lowshelf filter with a low Q value. The only difference would be that a "proper" tilt would act like a seesaw and raise one end of the spectrum while lowering the other. This can be achieved by adding a Gain filter with half the inverted Gain of the shelf.
Is that a good enough workaround?

**Comment by blbeczech82** [comment]
> Is that a good enough workaround?

Thank you for suggestion. I'll try later as it seems quite complicated (to me).
Anyway, can you add tilt eq on your low priority to-do list? Please?

**Comment by HEnquist** [comment]
Something like this?
Showing -10, -5, 0, 5 and 10 dB of tilt. It's implemented as two shelving filters. Using a single one as I suggested first makes the tilt quite wiggly, especially for small tilts. With two shelves it gets nice and straight for all tilts. 

![Tilt](https://user-images.githubusercontent.com/6504678/176269919-1b82960c-f436-4d62-a60a-04bb61b97acd.png)

**Comment by HEnquist** [comment]
Is that actually meaningful for music listening? Seems more like a tool used in music production.
