### ISSUE TITLE
Pulse: Specify a channel map

### ISSUE THREAD

**Issue by tiny69712** [HEnquist/camilladsp#224]
Hello, I'm working with CamillaDSP and Pulseaudio server.
As we can see, in "pulsedevice.rs", CamillaDSP will send to Pulse API an profile

`    let pulsedev_res = Simple::new(
        None,           // Use the default server
        "CamillaDSP",   // Our application’s name
        dir,            // We want a playback stream
        Some(&devname), // Use the default device
        "ToDSP",        // Description of our stream
        &spec,          // Our sample format
        None,           // Use default channel map
        Some(&attr),    // Use default buffering attributes
    );`

This profile asks Pulse sever to create a sink-input stream with a default channel map. 

So my question is, when I have a sink with a different channel map in Pulseaudio, how can I specify it with CamillaDSP and not use the default thing ?

**Comment by HEnquist** [comment]
How do you use channel maps? I checked quickly and it looks like its mainly used for naming channels, and for doing stuff like balance control. CamillaDSP only uses channel index internally, not sure how the channel map would fit in here.
