### ISSUE TITLE
The debug log becomes too messy after adding ValueHistory

### ISSUE THREAD

**Issue by peng1999** [HEnquist/camilladsp#230]
The below debug log now prints very long message and cause the `-v` level log unreadable because `pb_stat.signal_rms` contains many entries.

https://github.com/HEnquist/camilladsp/blob/40bece7de5c9168b0c12586a35a3a91fa87337a8/src/alsadevice.rs#L547-L550

I see various ways to solve this problem:
1. Log only the last entry of `signal_rms`
   ```diff
   -      avg_delay, pb_stat.signal_rms 
   +      avg_delay, pb_stat.signal_rms.get_last()
   ```
3. Log `signal_rms` in a separate `trace` level log.
   ```rust
   debug!("PB: buffer level: {avg_delay:.1}");
   trace!("signal rms: {:?}", pb_stat.signal_rms);
   ```

**Comment by HEnquist** [comment]
This has been fixed in the development branch for 2.0
