### ISSUE TITLE
Websocket command for external loudness volume

### ISSUE THREAD

**Issue by bitkeeper** [HEnquist/camilladsp#231]
Currently for loudness the reference is used against the camilladsp volume.
It is not always desirable to use the camilladsp volume as master volume.
In that situation it would be nice if a websocket command, just like with volume, is available to provide an external loudness volume as option in addition to the camilladsp volume.

This would make it possible to create solutions that use the volume setting from other sources like:
- alsa mixer
- mpd volume
- external hardware volume solutions (which aren't available from a mixer)

This also would make it possible to external 'tune' the presence of the loudness by using a volume multiplier.

**Comment by HEnquist** [comment]
I'm already considering improvements to the volume control (see for example https://github.com/HEnquist/camilladsp/issues/229).
I didn't think of this use case but it makes sense and should be included. 
I think just moving the reference level isn't enough though. If the external volume control comes after camilladsp in the chain, then lowering the volume will make the Loudness filter boost the high and low end. This will then lead to a gain >0 in those regions and may cause clipping at the camilladsp output. Instead this would need a modified loudness filter that does the loudness compensation by lowering the midrange.

**Comment by HEnquist** [comment]
> Instead this would need a modified loudness filter that does the loudness compensation by lowering the midrange.

I had completely forgotten about this point! Apart from that detail it's implemented in next20. I think I'll just add an optional parameter to the loudness filter to determine if it should attenuate to keep the gain below 0 dB.

**Comment by HEnquist** [comment]
Implemented in https://github.com/HEnquist/camilladsp/commit/548feb0d1f5dd83b3ba7a77ca30bd308c3530bcc
