### ISSUE TITLE
QQ about the convolver used

### ISSUE THREAD

**Issue by ElliottBridge** [HEnquist/camilladsp#235]
Does the convolver that is utilised in this program utilise oversampling? Thanks

**Comment by HEnquist** [comment]
No there is no oversampling in the convolver. What would be the benefit of that? It would come with a heavy performance penalty.

**Comment by ElliottBridge** [comment]
> No there is no oversampling in the convolver. What would be the benefit of that? It would come with a heavy performance penalty.

I've heard aliasing can sometimes happen in convolvers and that oversampling stops this from ever happening. Sorry if this is wrong, I'm still learning this side of stuff, I'm more of a mechanical/acoustic background rather than an electronic one

**Comment by HEnquist** [comment]
I don't think there is more to add here, closing.
