### ISSUE TITLE
Setting ALSA period size

### ISSUE THREAD

**Issue by siraaris** [HEnquist/camilladsp#236]
I'm working on a project that involves CamillaDSP playback to an ALSA AAF device.

ALSA AAF utilises an AVTB library to transmit from a talker (CamillaDSP's playback device, albeit with a plug for format conversion little endian to big endian as that's the only format that AVTP supports) to a listener (an active speaker with an ALSA AAF device configured to pick up the relevant AVTP frames, and slave to an 8ch DAC and subsequent 8 ch amplifier).

There is a requirement in the ALSA AAF plugin to set the period size as a multiple of the "frames per PDU" AAF device configuration, which is 6 for 44.1khz or 48khz, 12 for 88.2khz or 96khz, and 24 for 176.4khz or 192khz.

I notice that Camilla seems to set the period size to 64, 128, 256 etc depending on chunksize, hence I'm getting errors such as:

ALSA lib pcm_aaf.c:1164:(aaf_hw_params) Period size (256) must be multiple of frames_per_pdu (6)

when CamillaDSP starts.

Is it possible to set the period size (for ALSA) as a configuration option in Camilla?

Aris

**Comment by siraaris** [comment]
I use the following axfer command for testing, and have found that period ~300 and buffer ~600 works quite well for 48khz, 8ch audio.

It would be good to be able to pass in a manual buffer/period from a configurable to the ALSA device.

Aris


#!/bin/bash

SPEAKER="controller-8-KL"
PERIOD="300"
BUFFER="600"
TSTAMP="gettimeofday"
CHANNELS="8"

axfer transfer playback -vvv -f S32_LE -c $CHANNELS -r 48000 -t raw --xfer-type=libasound -D $SPEAKER --period-size=$PERIOD --buffer-size=$BUFFER --tstamp-type=$TSTAMP files/32b_LE_"$CHANNELS"CH.raw

exit 0

**Comment by HEnquist** [comment]
All Alsa devices I have tested allow the buffer and period sizes to be set very freely, and I have used that to simplify the Alsa backend. I set them to values such that a full chunk always fits in the buffer. And to be safe I set the requested buffer size to a power of two. Then, I use the `snd_pcm_hw_params_set_buffer_size_near()` and the corresponding one for period, to allow the device to suggest other values if the requested ones doesn't work. 
https://github.com/HEnquist/camilladsp/blob/master/src/alsadevice.rs#L435
The fact that this fails here looks like a limitation (or maybe a bug?) in the aaf plugin. When asked for a period of 256, it should return 252 or 258.

Decoupling the buffer and period sizes from the chunksize would make the alsa backend much more complicated, not something I'm very keen on doing. 
Can you get it to work if you modify the values used here to multiples of 6?
```
        let _bufsize = hwp.set_buffer_size_near(2 * bufsize)?;
        let _period = hwp.set_period_size_near(bufsize / 4, alsa::ValueOr::Nearest)?;
```
This is lines 435 and 436 in alsadevice.rs

**Comment by siraaris** [comment]
Agree, AAF should return near acceptable values. I started looking at Camilla code last night and was thinking along the lines you suggested. Will try tonight and let you know.

Thank you!

**Comment by siraaris** [comment]
I was working on the next11 branch. With master, the behaviour is better, with the period & buffer allocated appropriately:

2022-10-08 05:00:32.527514 DEBUG [src/alsadevice.rs:454] Opening audio device "controller-8-KL-aaf" with parameters: HwParams { channels: Ok(8), rate: "Ok(48000) Hz", format: Ok(S32LE), access: Ok(RWInterleaved), period_size: "Ok(312) frames", buffer_size: "Ok(2500) frames" }, SwParams(avail_min: Ok(1250) frames, start_threshold: Ok(938) frames, stop_threshold: Ok(2500) frames)

However, the process stops at a try again response:

2022-10-08 05:00:32.629050 INFO [src/alsadevice.rs:160] Starting playback from Prepared state
ALSA lib pcm_aaf.c:1044:(aaf_timer_timeout) Missed 3 expirations 
2022-10-08 05:00:32.682701 WARN [src/alsadevice.rs:212] Retrying playback, error: ALSA function 'snd_pcm_writei' failed with error 'EAGAIN: Try again'
2022-10-08 05:00:32.708937 ERROR [src/bin.rs:344] Playback error: ALSA function 'snd_pcm_writei' failed with error 'EAGAIN: Try again'
2022-10-08 05:00:32.708991 DEBUG [src/bin.rs:352] Wait for capture thread to exit..
ALSA lib pcm_aaf.c:1044:(aaf_timer_timeout) Missed 3 expirations 
ALSA lib pcm_aaf.c:672:(aaf_tx_pdu) Failed to send AAF PDU
2022-10-08 05:00:32.710554 WARN [src/alsadevice.rs:195] Playback device failed while waiting for available buffer space, error: ALSA function 'snd_pcm_wait' failed with error 'EIO: I/O error'
2022-10-08 05:00:32.722057 DEBUG [src/alsadevice.rs:620] Exit message received, sending EndOfStream
2022-10-08 05:00:32.722400 DEBUG [src/bin.rs:915] Restarting with new config
2022-10-08 05:00:32.722454 DEBUG [src/bin.rs:857] Wait for config
2022-10-08 05:00:32.722486 DEBUG [src/bin.rs:860] No config and not in wait mode, exiting!

**Comment by HEnquist** [comment]
Can you experiment to see if you can find a combination of buffer and period size that works with Camilla? You could try using a small chunksize, and modify the code to set the exact period and buffer (and perhaps also start threshold) you want. I would recommend capturing from /dev/zero with the File backend so you don't have to think about modifications to the Alsa code breaking the capture.

**Comment by siraaris** [comment]
I think the setting of period/buffer is a separate issue. If the period/buffer is not set correctly, the error is specific, and addressable, multiples of frames per pdu etc.

I think with period buffer set properly, the next problem relates to how to handle EAGAIN. I note that in the code you placehold whether to use recover or prepare?

I was testing with https://www.alsa-project.org/alsa-doc/alsa-lib/_2test_2pcm_8c-example.html where I can easily get the incorrect period/buffer error if I set these inappropriately, but on EAGAIN the example pcm.c code continues on instead of breaking.

**Comment by HEnquist** [comment]
I mentioned the period/buffer/thresholds because setting those inappropriately can give somewhat similar issues, but perhaps not the EAGAIN.
At the moment I only retry once on EAGAIN, this should of course be changed so it retries over and over until it succeeds of fails with some other error.
Could you try changing line 220 in alsadevice? 
https://github.com/HEnquist/camilladsp/blob/master/src/alsadevice.rs#L220
Replace `io.writei(buffer)?` with `0`:
```
    let frames = match io.writei(buffer) {
        Ok(frames) => frames,
        Err(err) => {
            warn!("Retrying playback, error: {}", err);
            if err.nix_error() != alsa::nix::errno::Errno::EAGAIN {
                trace!("snd_pcm_prepare");
                // Would recover() be better than prepare()?
                pcmdevice.prepare()?;
            }
            thread::sleep(Duration::from_millis(target_delay));
            0
        }
    };
```

**Comment by siraaris** [comment]
I modified alsadevice.rs as requested, out attached. I've also attached the actual/test config and the asound configuration file.

[camilladsp-yml.txt](https://github.com/HEnquist/camilladsp/files/9777593/camilladsp-yml.txt)
[camilladsp-asound-conf.txt](https://github.com/HEnquist/camilladsp/files/9777594/camilladsp-asound-conf.txt)
[camilladsp-output.txt](https://github.com/HEnquist/camilladsp/files/9777595/camilladsp-output.txt)

**Comment by siraaris** [comment]
Incidentally if I use GSTreamer for the AVTP transport, and use Loopback as the CamillaDSP playback (in order to pick up the stream in GST), then the result is quite stable.

**Comment by HEnquist** [comment]
Thanks for the logs (and sorry for the slow reply).
The mod I suggested was too simple, it needs a little more logic to handle the again error properly.

**Comment by HEnquist** [comment]
New issue specifically for the EAGAIN handling: https://github.com/HEnquist/camilladsp/issues/241

**Comment by siraaris** [comment]
Can close this issue, given the EAGAIN enhancement issue that's been created.
