### ISSUE TITLE
Any recommended HW for home?

### ISSUE THREAD

**Issue by jrbrodie77** [HEnquist/camilladsp#240]
(Let me know if there's a Discord or similar for this type of question)

If I wanted to make a 2 in / 6 or 8 channels out, any recommended soundcards and single board compute that you'd recommend?

**Comment by HEnquist** [comment]
There are a number of options for interfaces. Some (far from all) are listed here: https://github.com/HEnquist/camilladsp/blob/master/tested_devices.md
For SBC I would recommend to get something that can run with the latest kernels. A pi 4 works great, but others are also fine.
These threads have a lot more info:
https://www.diyaudio.com/community/threads/camilladsp-cross-platform-iir-and-fir-engine-for-crossovers-room-correction-etc.349818/
https://www.audiosciencereview.com/forum/index.php?threads/rpi4-camilladsp-tutorial.29656/
