### ISSUE TITLE
Address named volume filters via web socket

### ISSUE THREAD

**Issue by MaxiMars73** [HEnquist/camilladsp#243]
I'm playing around with pyCamillaDSP at the moment and would like to build a monitor controller for my studio.
It would be nice if you could address different volume filters via web socket. So you could crossfade between channels.
For instance:

```
cdsp = CamillaConnection("127.0.0.1", port)
cdsp.connect()

current_vol_a = cdsp.get_volume('Volume_A')
current_vol_b = cdsp.get_volume('Volume_B')

print(f"Current volume of Monitor A: {current_vol_a} dB")
print(f"Current volume of Monitor B: {current_vol_b} dB")

if current_vol_a > current_vol_b :
          cdsp.set_volume('Volume_B', current_vol_a)
          cdsp.set_volume('Volume_A', -100)
    else:
        cdsp.set_volume('Volume_A', current_vol_b)
        cdsp.set_volume('Volume_B', -100)

cdsp.disconnect()
```
That would be great!

And if you could do the same thing with the Mutes, that would be fantastic.

```
set_mute('MyMixer', 'destination_0', true)
set_mute('MyMixer', 'source_0', true)

```

**Comment by HEnquist** [comment]
I'm planning to add something that should work for this.
The idea is to add several volume settings. They should be arranged as a main one and a few extras. Each Volume filter can then specify which volume setting it reacts to. The existing commands for setting and getting volume will stay and control an always included main volume control. Then there will be new commands for setting and getting the extras. It's still on the idea stage, I'm planning to include it in v1.2.

Setting mute in a mixer can already be done with a little python code. Fetch the current config, look up the mixer by name, modify the mute properties as needed, and apply the modified config. This is easy enough that I don't think it's worth adding separate commands for it.

**Comment by HEnquist** [comment]
This is mostly covered by https://github.com/HEnquist/camilladsp/issues/229
Closing in favor of that one
