### ISSUE TITLE
Reading from Wav file

### ISSUE THREAD

**Issue by Foxenfurter** [HEnquist/camilladsp#260]
While testing my audio pipeline, I noticed that I could directly process a standard 44.1k 16bit wav file (with the appropriate YAML file)
But when trying to load a 96k 24 bit wav file I had to convert to raw before it would be processed. For example

My inbound Pipeline is

flac -dcs --totally-silent Misery.flac | **sox -q -t wav - -t raw -C 0 -r 96000 -b24 -  |** camilladsp.exe Develop9624.yml |

(i.e. with the sox transformation it works)

ffprobe  shows the output from the flac to be

Input #0, wav, from 'Misery_convfromflac.wav':
  Duration: 00:03:43.00, bitrate: 4608 kb/s
  Stream #0:0: Audio: pcm_s24le ([1][0][0][0] / 0x0001), 96000 Hz, stereo, s32 (24 bit), 4608 kb/s

my YAML entry looks like this
devices:
  samplerate: 96000
  buffersize: 2048
  
  capture:
    type: Stdin
    channels: 2
    format: S24LE3
  playback:
    type: Stdout
    channels: 2
    format: S24LE3

I am then running the output to a sox raw to wav converter.

Any ideas whether I can do away with the sox conversion?

**Comment by HEnquist** [comment]
The problem to solve is to figure out what data format it is, and where the data chunk starts and ends inside the file. You can use `skip_bytes` and `read_bytes` to tell camilladsp where to start and stop reading. There is a script here that can help you figure things out: https://github.com/HEnquist/camilladsp/blob/master/testscripts/analyze_wav.py

**Comment by Foxenfurter** [comment]
Thanks - I ran the script vs both 44.1/16bit file and 96/24 files - the 16 bit file worked OK. But I got the following errors from running the 24 bit files

DEBUG:root:Found chunk of type fmt , length 40
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-9-b77e2f460d56> in <module>
      2     import sys
      3     #info = read_wav_header(sys.argv[1])
----> 4     info = read_wav_header("E:\\Local Audio\\CamillaDSP\\camilladsp-windows-amd64\\Misery_convfromflac.wav")
      5     print("Wav properties:")
      6     for name, val in info.items():

<ipython-input-8-c9b6e0a286ca> in read_wav_header(filename)
     63         chunk_length = struct.unpack('<L', buf_header[4:8])[0]
     64         logging.debug("Found chunk of type {}, length {}".format(chunk_type, chunk_length))
---> 65         analyze_chunk(chunk_type, next_chunk_location, chunk_length, file_in, wav_info)
     66         next_chunk_location += (8 + chunk_length)
     67         if next_chunk_location >= input_filesize:

<ipython-input-8-c9b6e0a286ca> in analyze_chunk(type, start, length, file, wav_info)
      2     if type == "fmt ":
      3         data = file.read(length)
----> 4         wav_info['SampleFormat'] = sampleformats[struct.unpack('<H', data[0:2])[0]]
      5         wav_info['NumChannels'] = struct.unpack('<H', data[2:4])[0]
      6         wav_info['SampleRate'] = struct.unpack('<L', data[4:8])[0]

KeyError: 65534

**Comment by HEnquist** [comment]
Ok that means the file has an extended header that the script can't decode. Try this one instead: https://github.com/HEnquist/pycamilladsp-plot/blob/master/camilladsp_plot/audiofileread.py

**Comment by Foxenfurter** [comment]
Thanks - that worked.

So my understanding of the wav format, having just done a little reading is that the raw data starts immediately after the word "data" in the filestream; and this should follow a pattern that is driven by the exact format itself, but there is no enforcement of this.

I have just checked a number of flac files with 24/96 content and the most common seems to be

dataoffset : 68
datalength : 167571456
sampleformat : S24LE3
bitspersample : 24
channels : 2
byterate : 576000
samplerate : 96000
bytesperframe : 6

However those that have been dynamically created from sox have  a dataoffset of 80 rather than 68.

So are you suggesting that the alternative to letting sox convert to a raw file is that I do the calculations and add these into the camilla yaml file at run-time? Or have I misunderstood?

**Comment by HEnquist** [comment]
> So my understanding of the wav format, having just done a little reading is that the raw data starts immediately after the word "data" in the filestream; and this should follow a pattern that is driven by the exact format itself, but there is no enforcement of this.

That should be true most of the time, but the only way to be sure is to parse the header. Relying on the word "data" won't always work out.
 
> 
> I have just checked a number of flac files with 24/96 content and the most common seems to be
> 
> dataoffset : 68 datalength : 167571456 sampleformat : S24LE3 bitspersample : 24 channels : 2 byterate : 576000 samplerate : 96000 bytesperframe : 6
> 
You mean flacs that were converted to WAV, right?

> However those that have been dynamically created from sox have a dataoffset of 80 rather than 68.
> 
Other offset values are also possible! There are quite a few variations of the WAV header with different lengths. There may also be metadata blocks before the audio data, and then the offset becomes much larger. It's rare, but these blocks may also come after the audio data. Because of that it's a good idea to check the length of the data block and only read that. Metadata typically doesn't sound very good..

> So are you suggesting that the alternative to letting sox convert to a raw file is that I do the calculations and add these into the camilla yaml file at run-time? Or have I misunderstood?

Yes exactly, you can look at the wav header to figure out where the data is (and what it is), and adjust the yaml as needed.

**Comment by Foxenfurter** [comment]
You mean flacs that were converted to WAV, right? No, sorry wasn't clear - they were flacs from different sources that contained 24/96 WAV files and I unpacked them to WAV and then ran them vs the tester.

I thought that's what you meant :) the c# library I am using contains handlers for this, but I have been limiting my use of it as it makes my head hurt.

My technology background is software development for Finance Applications and I have been doing engineering management rather than hands-on coding. I must admit it hadn't registered to me that CamillaDSP is really more of an OS Level utility and wouldn't by design use wav files as a source, but it makes sense to me now.

Anyway thanks for you help on this, I really appreciate it.
