### ISSUE TITLE
Overall Gain not being applied at higher samplerates?

### ISSUE THREAD

**Issue by Foxenfurter** [HEnquist/camilladsp#262]
I now have dynamic sample-rates working with my plugin and I am testing this in LMS pipeline. To do this I have up-sampled the same short track from 16 44 up to 24 192 with all rates in between and played them as an album. Not the most exciting listen, but hey ho.

Technically everything appears to be working, in that a revised yaml file is created with the correct rates in and any fir filters resampled, and I get undistorted music with every rate.

However, I have a Overall Gain setting ( I am calling it Preamp in my filter), and this seems to be ignored when the higher rates are running. I checked the same tracks on pass-through mode where no DSP is applied and the gain is the same across all tracks.

I then reduced the preamp to a lower level and the difference was even more apparent. I noted that you were looking at having a persistent overall gain setting as an upgrade is the issue that I am seeing related?

**Comment by HEnquist** [comment]
Is there a particular rate where things start misbehaving, or is a gradual change with increasing rate? Can you show a pair of generated config? One for a high samplerate, and one for a low one.
How are you resampling the fir filters?

The overall gain you mention is an improvement to the current volume control. I'm not aware of any issues with the current one, except that it's not as user friendly as it could be.

**Comment by Foxenfurter** [comment]
I have isolated the issue to only occurring when running FIR filters, and it seems that the effective volume **does** increase with rate. It is slightly noticeable at 24/96 and very noticeable at 24/192

The command to resample the filter in this case is
sox.exe "C:\ProgramData\Squeezebox\prefs\SqueezeDSP\Impulses\Cavern4Iloud.wav" -r 96000 "C:\ProgramData\Squeezebox\prefs\SqueezeDSP\Temp\96000_00F12EE86F_Impulses_Cavern4Iloud.wav"

with only the rate changing - I am using this approach even if the source and target rate are the same. 

Here is an example of 2 yaml files
#------------------44 / 16
devices:
  samplerate : 44100
  buffersize : 2048
  capture : 
    type : Stdin
    channels : 2
    format : S16LE
  playback : 
    type : Stdout
    channels : 2
    format : S16LE
filters:
  Preamp:
    type: Gain
    parameters:
      gain: -10.2
  EQBand_0:
    type: Biquad
    parameters:
      gain: 0
      q: 1.41
      freq: 60
      type: Peaking
  EQBand_1:
    type: Biquad
    parameters:
      gain: 0
      q: 2.1
      freq: 15360
      type: Peaking
  FirFilter_0:
    type: Conv
    parameters:
      type: Wav
      channel: 0
      filename: C:\ProgramData\Squeezebox\prefs\SqueezeDSP\Temp\44100_00F12EE86F_Impulses_Cavern4Iloud.wav
  FirFilter_1:
    type: Conv
    parameters:
      type: Wav
      channel: 1
      filename: C:\ProgramData\Squeezebox\prefs\SqueezeDSP\Temp\44100_00F12EE86F_Impulses_Cavern4Iloud.wav
pipeline:
  - type: Filter
    channel: 0
    names: 
      - Preamp
      - EQBand_0
      - EQBand_1
      - FirFilter_0

  - type: Filter
    channel: 1
    names: 
      - Preamp
      - EQBand_0
      - EQBand_1
      - FirFilter_1



#------------------96 / 24
devices:
  samplerate : 96000
  buffersize : 2048
  capture : 
    type : Stdin
    channels : 2
    format : S24LE3
  playback : 
    type : Stdout
    channels : 2
    format : S24LE3
filters:
  Preamp:
    type: Gain
    parameters:
      gain: -10.2
  EQBand_0:
    type: Biquad
    parameters:
      gain: 0
      q: 1.41
      freq: 60
      type: Peaking
  EQBand_1:
    type: Biquad
    parameters:
      gain: 0
      q: 2.1
      freq: 15360
      type: Peaking
  FirFilter_0:
    type: Conv
    parameters:
      type: Wav
      channel: 0
      filename: C:\ProgramData\Squeezebox\prefs\SqueezeDSP\Temp\96000_00F12EE86F_Impulses_Cavern4Iloud.wav
  FirFilter_1:
    type: Conv
    parameters:
      type: Wav
      channel: 1
      filename: C:\ProgramData\Squeezebox\prefs\SqueezeDSP\Temp\96000_00F12EE86F_Impulses_Cavern4Iloud.wav
pipeline:
  - type: Filter
    channel: 0
    names: 
      - Preamp
      - EQBand_0
      - EQBand_1
      - FirFilter_0

  - type: Filter
    channel: 1
    names: 
      - Preamp
      - EQBand_0
      - EQBand_1
      - FirFilter_1

**Comment by Foxenfurter** [comment]
NB my YAML file indentation was mucked up when I pasted it! The actual files are properly indented

**Comment by Foxenfurter** [comment]
Sorry to bombard you with questions - but I have also been testing gapless playback as this is a requirement on LMS.

I am finding that there is a very small but noticeable pause in music streams when the yaml file contains a convolution filter. The delay disappears if I remove the filter. At first I thought it was my wrapper code, but in testing the above I noticed that the glitch disappeared when I simplified the filter, and re-appeared when I added it back.

**Comment by HEnquist** [comment]
Alright, the gain issue is caused by resampling the IR! Probably easiest to explain with an example.
Say that you have this IR: `0, 0, 0.5, 0.5, 0, 0`
A simple boxcar lowpass. The gain at low frequencies is the sum of the coefficients, which is 1.0.
Now we resample this from 44.1 kHz to 88.2 kHz. I'll use simple linear interpolation (since it can be done by hand).
The result is twice as long: `0, 0, 0, 0.25, 0.5, 0.5, 0.5, 0.25, 0, 0, 0`
Now we'll calculate the LF gain again by summing. This becomes 2.0! 

To fix this, you need to adjust the gain after resampling the IR. Either you divide the IR with `fs_new/fs_old`, or adjust your preamp gain filter by the same amount. Adjusting the gain filter is likely the easiest, just recalculate the ratio to dB.

**Comment by HEnquist** [comment]
> I am finding that there is a very small but noticeable pause in music streams when the yaml file contains a convolution filter. The delay disappears if I remove the filter. At first I thought it was my wrapper code, but in testing the above I noticed that the glitch disappeared when I simplified the filter, and re-appeared when I added it back.

Does LMS launch a camilladsp process for every file, or does it keep piping data to the same process for several songs if the rate doesn't change?
If it launches a new process for every time, then it won't be possible to get it completely gapless. The FIR filters introduce a delay, so the start of the track gets delayed by half the length of the IR, and the end is cut short by the same amount (unless you use the extra_samples parameter to flush some more data through).

**Comment by Foxenfurter** [comment]
> Alright, the gain issue is caused by resampling the IR!
> To fix this, you need to adjust the gain after resampling the IR. Either you divide the IR with fs_new/fs_old, or adjust your preamp gain filter by the same amount. Adjusting the gain filter is likely the easiest, just recalculate the ratio to dB.

Before I do anything, can I check whether I actually need to resample the Impulse at all, as a close reading of your documentation suggests to me that it is not necessary, and I may have created a problem where non exists. i.e. under the documentation for fir filters and for wav files you say " The sample rate of the file is ignored."

**Comment by Foxenfurter** [comment]
> Does LMS launch a camilladsp process for every file?
Yes
> If it launches a new process for every time, then it won't be possible to get it completely gapless. The FIR filters introduce a delay, so the start of the track gets delayed by half the length of the IR, and the end is cut short by the same amount (unless you use the extra_samples parameter to flush some more data through).

Sounds like I have been trying to get CamillaDSP to do something that it was not designed for. I think I will have to revert back to using my legacy impulse convolver as that computes the gain and avoids the gaps via an intermediary buffer, at the expense of additional latency and extra CPU usage.

**Comment by HEnquist** [comment]
> 
> Before I do anything, can I check whether I actually need to resample the Impulse at all, as a close reading of your documentation suggests to me that it is not necessary, and I may have created a problem where non exists. i.e. under the documentation for fir filters and for wav files you say " The sample rate of the file is ignored."

The sample rate info stored in the WAV is ignored, instead it assumes that the file is made for the right sample rate. This means it will gladly use a 44.1 kHz wav IR to filter 96kHz audio. That runs but the frequency response will not be correct. You need to either resample the IR to fit the audio, or resample the audio to fit the IR.

**Comment by Foxenfurter** [comment]
>it assumes that the file is made for the right sample rate

Understood!

**Comment by HEnquist** [comment]
I believe the main issue here was sorted out. Please reopen if there are still problems with this.
