### ISSUE TITLE
Problem building camilladsp-1.0.3 with Rustc 1.67

### ISSUE THREAD

**Issue by aci996** [HEnquist/camilladsp#267]
*****************
Raspberry Pi4
Raspi os 64bit

camilladsp-1.0.3

rustc 1.67.1 (d5a82bbd2 2023-02-07)
cargo 1.67.1 (8ecd4f20a 2023-01-10)

(installed via curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh)

build flags:
RUSTFLAGS='-C target-feature=+neon -C target-cpu=native' cargo build --release --features jack-backend

*****************

warning: an associated function with this name may be added to the standard library in the future
   --> src/cpaldevice.rs:368:45
    |
368 | / ...                   debug!(
369 | | ...                       "Current buffer level {:.1}, set capture rate to {:.4}%",
370 | | ...                       av_delay,
371 | | ...                       100.0 * speed
372 | | ...                   );
    | |_______________________^
    |
    = warning: once this associated item is added to the standard library, the ambiguity may cause an error or change in behavior!
    = note: for more information, see issue #48919 <https://github.com/rust-lang/rust/issues/48919>
    = help: call with fully qualified syntax `NewValue::new(...)` to keep using the current method
    = note: `#[warn(unstable_name_collisions)]` on by default
    = note: this warning originates in the macro `format_args` which comes from the expansion of the macro `debug` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0061]: this function takes 1 argument but 0 arguments were supplied
   --> src/cpaldevice.rs:368:45
    |
368 | / ...                   debug!(
369 | | ...                       "Current buffer level {:.1}, set capture rate to {:.4}%",
370 | | ...                       av_delay,
371 | | ...                       100.0 * speed
372 | | ...                   );
    | |_______________________^ an argument of type `core::fmt::UnsafeArg` is missing
    |
note: associated function defined here
   --> src/lib.rs:60:8
    |
60  |     fn new(val: T) -> Self;
    |        ^^^
    = note: this error originates in the macro `format_args` which comes from the expansion of the macro `debug` (in Nightly builds, run with -Z macro-backtrace for more info)
help: provide the argument
   --> |/home/magnus/.cargo/registry/src/github.com-1ecc6299db9ec823/log-0.4.17/src/macros.rs:241:32
    |
241 |         format_args!($($args)*)(/* core::fmt::UnsafeArg */)
    |                                ++++++++++++++++++++++++++++

For more information about this error, try `rustc --explain E0061`.
warning: `camilladsp` (lib) generated 1 warning
error: could not compile `camilladsp` due to previous error; 1 warning emitted
warning: build failed, waiting for other jobs to finish...

Regards //Magnus

**Comment by HEnquist** [comment]
This is because of some changes in rustc 1.67. It's already taken care of in the development branch for version 2.0 (next20). Let's keep this issue open until that is merged.
