### ISSUE TITLE
error flexi_logger

### ISSUE THREAD

**Issue by balbuze** [HEnquist/camilladsp#268]
hello,
Is this message from CamillaDsp?
```

tail -f /var/log/mpd.log 
[flexi_logger][ERRCODE::Write] writing failed, caused by Permission denied (os error 13)
See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#write
[flexi_logger][ERRCODE::Write] writing failed, caused by Permission denied (os error 13)
See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#write
[flexi_logger][ERRCODE::Write] writing failed, caused by Permission denied (os error 13)
See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#write
[flexi_logger][ERRCODE::Write] writing failed, caused by Permission denied (os error 13)
See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#write
[flexi_logger][ERRCODE::Write] writing failed, caused by Permission denied (os error 13)
See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#write

**Comment by HEnquist** [comment]
Yes, flexi_logger is the logging library it uses.

**Comment by balbuze** [comment]
why this error?

**Comment by HEnquist** [comment]
Is camilladsp writing logs to a file, or just to stdout?

**Comment by balbuze** [comment]
To a file /tmp/camilladsp.log

**Comment by HEnquist** [comment]
So then it seems like there is a permissions issue. The user account that runs the Camilla process doesn't have write access for that file.

**Comment by balbuze** [comment]
Weird because the file is created and contents the log. But I'll test with an other location.
Thanks

**Comment by HEnquist** [comment]
Could it happen that the file already exists but is owned by another user?

**Comment by balbuze** [comment]
Hello.
I changed location for the log. Same result. The file is created when Camilla first start. But it can't be rewrite when Camilla restarts (play, stop). It is created with permission : 
```
           
volumio@volumio-rpi4:~$ ls -axl /var/log/camilladsp.log 
-rw-r--r-- 1 volumio volumio 15667 Mar  3 16:39 /var/log/camilladsp.log
```
Changing mode to 777 fix the problem. But it is not possible to do it each start.
Any hint?

**Comment by HEnquist** [comment]
So rw-r--r-- already gives the file owner write access to the file. I guess camilladsp runs as a different user than "volumio" after it restarts. Can you check that?

**Comment by HEnquist** [comment]
Can this be closed?

**Comment by balbuze** [comment]
Hello! yes, I found how to fix it by creating the file, setting permissions before CamillaDsp first start.
TY
