### ISSUE TITLE
Stop command causes camilladsp to exit

### ISSUE THREAD

**Issue by kbasaran** [HEnquist/camilladsp#273]
I am trying to make CamillaDSP completely stop processing and release the audio device in certain instances to save power. This I tried to do with the 'Stop' command yet the 'Stop' command does the exact same thing with 'Exit' for me and the application is terminated quietly, the websocket is closed. I expected it to go into "Inactive" mode and wait for a new config.

Here the websocket response
```
>>> ws = create_connection("ws://127.0.0.1:1234")
>>> ws.send(json.dumps("Stop"))
12
>>> print(self.ws.recv())
{"Stop":{"result":"Ok"}}
```

**Comment by HEnquist** [comment]
Are you starting Camilladsp with the wait flag, -w?

**Comment by kbasaran** [comment]
No I wasn't. That indeed solves the problem. Did I miss this in documentation?
