### ISSUE TITLE
Add possibility to include other config files from within main config file and alias channels

### ISSUE THREAD

**Issue by Michal-Szczepaniak** [HEnquist/camilladsp#276]
Since my previous issue, i got couple ideas for easy improvement. 

Since you don't want to load other noncamilladsp files then my idea is to load other camilladsp files. for example i could put all filter definitions in separate file and then just inclue that file, that would simplify main file and should be much of a change.

secondly, with many channels mixing and mapping it would be nice if you could add possibilty to alias channels like L -> 0, R ->1 etc but that's less important. Loading other files would declutter 1200 lines long configs massively

**Comment by HEnquist** [comment]
Including other files may look like a simple thing but it would make things much more complicated. There are many reasons for keeping the config a single object. The exception is of course the FIR filter coefficient files, where there is no other choice. They make things much harder for example for the gui. I don't want more of that!

Aliases may come at some point if I come up with a good design. 

Could you use yaml anchors to shorten and simplify your config?
https://support.atlassian.com/bitbucket-cloud/docs/yaml-anchors/

**Comment by HEnquist** [comment]
Closing this since there is no planned work.
