### ISSUE TITLE
Compilation Requirements

### ISSUE THREAD

**Issue by rawdlite** [HEnquist/camilladsp#279]
This is minor.
When trying to compile on a fresh dietpi install i noticed an additional

`sudo apt install librust-signal-hook-dev, clang `

is required to compile. 
This is just to let you know. You might find it worth adding to the compile instructions.

Cheers

**Comment by HEnquist** [comment]
Thanks, I thought a bit about what to do with this. I realised there are too many distributions so any attempt I make to cover them all will get outdated quickly.
Instead I added a note about different distributions: https://github.com/HEnquist/camilladsp/commit/c42420f34a9814c67634f585dd12b5f29fd35312
