### ISSUE TITLE
Bypassing empty processing pipeline?

### ISSUE THREAD

**Issue by pavhofman** [HEnquist/camilladsp#283]
CDSP has become the best tool for bridging capture and playback audio interfaces. It provides everything necessary including rate adjust or efficient adaptive resampling.

Would it perhaps make sense to bypass the processing thread if the pipeline is empty (i.e. plain bridge), avoiding the latency overhead/risk of late response incurred by the extra thread? IIUC the modification would be simple, because channels linking capture -> processing and processing -> playback are compatible and they are created and assigned in one common method (BTW which shows the excellent design of CDSP).

**Comment by HEnquist** [comment]
It would be possible but there would be some disadvantages. First one is that the default volume control is done in the processing thread. That could be handled by moving it to the capture thread.
It would also mean that it's not possible to do gapless switching between a config that has some filtering and one that doesn't. Not having a processing thread means there is only a single channel between capture and playback, and at least one side would need to be closed to insert another channel to route the data through the processing thread.
Perhaps skipping processing could be determined by a new config option or command line parameter.

As a first step it's probably a good idea to try it to see if there are any noticeable advantages in practice. It would be quite quick to modify the code to completely omit the processing thread. A bit crude but should work well enough for evaluating :)

**Comment by pavhofman** [comment]
> It would be possible but there would be some disadvantages. First one is that the default volume control is done in the processing thread. That could be handled by moving it to the capture thread.

Would it make sense to have the volume as the last operation, i.e. possibly in the playback thread? Probably not critical as the DSP runs in float64 with lots of precision.

> It would also mean that it's not possible to do gapless switching between a config that has some filtering and one that doesn't. Not having a processing thread means there is only a single channel between capture and playback, and at least one side would need to be closed to insert another channel to route the data through the processing thread. Perhaps skipping processing could be determined by a new config option or command line parameter.

I think the extra parameter would be the best choice. User would explicitely ask to shun all the processing features (perhaps excluding the volume control) and use CDSP as a plain bridge - effectively replacing the buggy alsaloop. If  operations concerning the DSP stop working or have no effect - that's what the user asked for.

> 
> As a first step it's probably a good idea to try it to see if there are any noticeable advantages in practice. It would be quite quick to modify the code to completely omit the processing thread. A bit crude but should work well enough for evaluating :)

Theoretically the effect is logical - having to wake up two instead of three threads to pass data between IN and OUT.

Practically -  perhaps that would take some kind of "xrun-free minimum buffer size" test with controlled external CPU load. Ideally if this could be integrated into rust, like some controlled CPU extra load within the bench infrastructure - but I could not find anything related in the cargo bench docs. Maybe such a test/bench would be quite handy for checking on performance effects of future changes in the critical paths - if such a bench test were easy to setup/run. But honestly right now I have no specific idea how that would be implemented in some rust idiomatic way.

**Comment by HEnquist** [comment]
> Would it make sense to have the volume as the last operation, i.e. possibly in the playback thread?

That would put it after any dither filter, making dithered volume control impossible. Bit of a shame. Putting it in the capture thread (after the conversion to float64) shouldn't cause any precision issues.

**Comment by HEnquist** [comment]
Completely skipping the volume is maybe fine in a pipeline-less mode. But I just thought of another complication. If resampling is used, then it's also a very good idea to put in a few dB of attenuation to avoid clipping on intersample overs. That gain also needs the processing thread. I could of course also be placed in either the capture or playback thread, but I would really prefer to keep the processing in those to the bare minimum.

**Comment by HEnquist** [comment]
I have thought of this a bit and decided against implementing it. The reason is mainly that it gives a fair bit of additional complexity, while not adding any value for the use cases camilladsp is mainly intended for.
