### ISSUE TITLE
next20 macOS playback format issue

### ISSUE THREAD

**Issue by siraaris** [HEnquist/camilladsp#284]
On the next20 branch, using a RME Digiface as the playback device returns an error on startup:

2023-05-25 01:45:20.682791 ERROR [src/bin.rs:355] Playback error: Failed to find matching physical playback format

  playback:
    type: CoreAudio
    channels: 64
    device: "Digiface AVB (23913580)"
    format: FLOAT32LE

Startup is OK with BlackHole:

  playback:
    type: CoreAudio
    channels: 64
    device: "BlackHole 64ch"
    format: FLOAT32LE

Realise this is an unreleased version, just submitting defect in case this hasn't cropped up yet.

**Comment by siraaris** [comment]
Should have said - the Digiface runs fine on v1.03.

**Comment by HEnquist** [comment]
This is likely because the config for CoreAudio devices changed. Before there was the `change_format ` setting that determined if the device should be switched to another format or not. When this was set to false or left out, the `format` was ignored. In next20 it's simplified, `change_format` is gone and instead setting `format` to something other than null will make it switch. That means that the chosen format must be one the device hardware can actually handle. Or null to just use the currently selected format.

See: https://github.com/HEnquist/camilladsp/blob/next20/backend_coreaudio.md#sample-format

**Comment by siraaris** [comment]
Understood.

With v1.03, if I explicitly set change_format: true on playback, the same error occurs. No problem there, with v1.03 I can set change_format: false or not have it set and playback works.

With v2, I remove the format: config line, and now camilladsp starts, but there is no audio presented on playback.

Here's what "Audio MIDI Setup" shows for the Digiface:

<img width="302" alt="Screenshot 2023-05-25 at 4 43 48 am" src="https://github.com/HEnquist/camilladsp/assets/12581268/d61a6f95-9853-4a34-9b82-5de54e9efa25">

**Comment by siraaris** [comment]
For completeness, listdevices presents:

  Device: "Digiface AVB (23913580)"
  ============================================================

    Capture
    ------------------------------------------------------------
    Default input stream config:
      channels: 8, samplerate: 192000, format: FLOAT32LE
    All supported input stream configs:
      channels: 128, samplerate min: 32000 max: 32000, format: FLOAT32LE
      channels: 128, samplerate min: 44100 max: 44100, format: FLOAT32LE
      channels: 128, samplerate min: 48000 max: 48000, format: FLOAT32LE
      channels: 128, samplerate min: 64000 max: 64000, format: FLOAT32LE
      channels: 128, samplerate min: 88200 max: 88200, format: FLOAT32LE
      channels: 128, samplerate min: 96000 max: 96000, format: FLOAT32LE
      channels: 128, samplerate min: 128000 max: 128000, format: FLOAT32LE
      channels: 128, samplerate min: 176400 max: 176400, format: FLOAT32LE
      channels: 128, samplerate min: 192000 max: 192000, format: FLOAT32LE

    Playback
    ------------------------------------------------------------
    Default output stream config:
      channels: 8, samplerate: 192000, format: FLOAT32LE
    All supported output stream configs:
      channels: 128, samplerate min: 32000 max: 32000, format: FLOAT32LE
      channels: 128, samplerate min: 44100 max: 44100, format: FLOAT32LE
      channels: 128, samplerate min: 48000 max: 48000, format: FLOAT32LE
      channels: 128, samplerate min: 64000 max: 64000, format: FLOAT32LE
      channels: 128, samplerate min: 88200 max: 88200, format: FLOAT32LE
      channels: 128, samplerate min: 96000 max: 96000, format: FLOAT32LE
      channels: 128, samplerate min: 128000 max: 128000, format: FLOAT32LE
      channels: 128, samplerate min: 176400 max: 176400, format: FLOAT32LE
      channels: 128, samplerate min: 192000 max: 192000, format: FLOAT32LE

**Comment by HEnquist** [comment]
Ok, then there is something else going on. Can you start with -vv and post the log here?

**Comment by siraaris** [comment]
Config and debug output in attached files.

[myconfig.txt](https://github.com/HEnquist/camilladsp/files/11558867/myconfig.txt)


[next20-debug.txt](https://github.com/HEnquist/camilladsp/files/11558831/next20-debug.txt)

**Comment by HEnquist** [comment]
Looks like you are setting the volume to -80 dB and then never changing it? Apart from that it looks fine.

**Comment by siraaris** [comment]
Oh. I think I need to update the volume integration between Roon and CamillaDSP for v2. 

Ok, let me check tomorrow and I reckon I'll close this with egg on face.

**Comment by HEnquist** [comment]
BTW it would be interesting to see a log (with -vv) from a failed start when format is set to FLOAT32LE. It looks like that should work..

**Comment by siraaris** [comment]
So, I set/increase the Volume (via websocket) but no sound is coming out. 

I suspect something has changed in v2 with Faders, but it's not clear what a configuration and web socket approach would be. 

I set volume as per v1 but adding the fader:

filters:
  #
  # Basic Volume Control
  #
  volume:
    type: Volume
    parameters:
      ramp_time: 200.0
      fader: Aux1

and Mixer Filters have volume:

  - type: Mixer
    name: multichannel

  #
  # K E Y S T O N E   ( L E F T )
  #

  #
  # Keystone Left - Right Woofer
  #
  - type: Filter
    channel: 0
    names:
      - keystone-gain-side-woofer
      - keystone-acourate-side-woofer-L
      - keystone-delay-side-woofer
      - volume

I'll spend some more time reading the docs, I'm sure I'll work it out - but pointers welcome :)

**Comment by HEnquist** [comment]
I thought there would be more trace output when it tries setting the format. That would be really useful so I'll add some more.

The new version has a default "main" volume control that is always enabled for all channels. You use both that one and one of the other faders, and both are being set to -80dB at the start. If you don't want to use main, make sure to set it to 0 dB. Then the other one should work ok.

**Comment by siraaris** [comment]
Got it. Needed to set the Fader volume etc.

**Comment by siraaris** [comment]
Happy to run with more trace when trying to get the format. I assume that it's because the Digiface is a 128ch in/out device, setup as 16 x 8 streams. I configure it in Camilla only for the channels I use (4 streams, each of 8 channels = 32ch).

Suspect the matching of what CoreAudio reports and what you match is off-whack, eg. missing some parameters that are not present in most CoreAudio devices (e.g. Streams)?

**Comment by siraaris** [comment]
<img width="1180" alt="Screenshot 2023-05-26 at 1 17 23 am" src="https://github.com/HEnquist/camilladsp/assets/12581268/2f222666-bb6a-47f6-a907-240b7cc15028">

**Comment by siraaris** [comment]
> I thought there would be more trace output when it tries setting the format. That would be really useful so I'll add some more.
> 
> The new version has a default "main" volume control that is always enabled for all channels. You use both that one and one of the other faders, and both are being set to -80dB at the start. If you don't want to use main, make sure to set it to 0 dB. Then the other one should work ok.

If I want to simply use the Main and automatically set the Fader (Aux1) to "0", is there a configured way to do this? I can run a script to set it, but would prefer to be able to set the defaults.

**Comment by siraaris** [comment]
Thank you, obvious now that you mention it and I've finished reading/getting my head across the documentation.

**Comment by HEnquist** [comment]
I added some trace logging of available formats in next20. Could you try it on the digiface?

**Comment by siraaris** [comment]
[next20-coreaudio-formats-debug.txt](https://github.com/HEnquist/camilladsp/files/11580984/next20-coreaudio-formats-debug.txt)

As requested.

**Comment by siraaris** [comment]
That's with explicitly stating the format for the playback device as FLOAT32LE

**Comment by HEnquist** [comment]
Thanks! It only lists the available formats for a single stream, another call would be needed to know how many streams are available.
At 192 kHz it's supposed to support 32 channels. Is that 4 streams of 8 channels each then? How does it work when you set the first stream to 192 kHz? Do all streams change to 192 kHz then? And does then stream 5 and up somehow become unavailable?

**Comment by siraaris** [comment]
The device can be setup as 4 Streams x 8 channels each (which is what I do), but I think it could also be set it up differently as long as the maximum was 32ch for input, as I use 192KHz SR.

e.g. a configuration with 6 Streams total, 4 with 4 channels and 2 with 8 channels is possible. In AVB I think there is also a maximum number of channels you can define per Stream (8).

The SR is set at the AVB Controller where the AVB routing is also configured. 

Overall I think the configuration of the device and SR must fall within bounds of the device's capability.

Are the number of Streams and Channels per Stream important to know, or just the SR and total number of Channels?

**Comment by siraaris** [comment]
Hence - I think that Apple MIDI Setup stating 192khz means that all streams are at 192khz. I think the 8ch report is maybe just because AVB streams are at most 8ch.

**Comment by HEnquist** [comment]
Thanks!
It seems like it's not that easy to figure out how many channels are actually supported then. The "listdevices" tool (that relies on the CPAL library) did better than camilladsp but didn't get it right either, listing 128 channels for all rates.
This only affects the switching of the physical sample format. Since that can be done manually, it's probably not worth spending too much time on this.

**Comment by siraaris** [comment]
Agree!
