### ISSUE TITLE
 unknown variant `Jack`, when build with --features jack-backend on windows

### ISSUE THREAD

**Issue by alex-vyverman** [HEnquist/camilladsp#304]
**Describe the bug**
I have an issue with v2 alpha5.
I wanted to try out jack, but it doesn't seem to ben working. 
When I start using 
`  capture:
    channels: 8
    device: default
    type: Jack

  playback:
    channels: 8
    device: default
    type: Jack`

I get `2023-10-30 22:17:23.802211 ERROR [src\socketserver.rs:1134] Error parsing yaml: devices.capture.type: unknown variant `Jack`, expected one of `File`, `Stdin`, `Wasapi` at line 7 column 11`, while I have build using `cargo build --release --features jack-backend`

It looks like it hasn't build the jack backend properly. There are a fair bit of warnings during compiling which I attached.

**To Reproduce**
1. build using `cargo build --release --features jack-backend --features cpal-backend` on win10 x64
2. start jackd (optional)
3. run camilladsp with jack backend

**System info**
- Win10 64bit
- x64
- CamillaDSP 2.0.0-alpha5

**Configuration**
[win_jack8ch.yml.txt](https://github.com/HEnquist/camilladsp/files/13210006/win_jack8ch.yml.txt)

**Logs**
[warnings.log](https://github.com/HEnquist/camilladsp/files/13209955/warnings.log)
2023-10-30 22:17:23.802211 ERROR [src\socketserver.rs:1134] Error parsing yaml: devices.capture.type: unknown variant `Jack`, expected one of `File`, `Stdin`, `Wasapi` at line 7 column 11

**Comment by HEnquist** [comment]
Jack support is provided by cpal, and the problem here is that cpal doesn't support Jack on windows, only Linux. The warnings are basically all about unused code. It compiles the cpal backend, but since jack isn't supported and no other backend uses it, the cpal backend becomes unusable and inaccessible.

**Comment by HEnquist** [comment]
I see that the readme is quite misleading here. I'll update to make it clear that jack is only supported on Linux.

**Comment by alex-vyverman** [comment]
That clears it up. Thanks!
