### ISSUE TITLE
Camiladsp 2.0 stop working on loopback ( 32bit os) 

### ISSUE THREAD

**Issue by melomane63** [HEnquist/camilladsp#310]
Using CamillaDSP 2.0.0, pi zero W 2, Raspberry Pi OS lite 32bit ( latest or legacy ). 

Camiladsp 2.0 stop working after somes seconds if input is on loopback ( hw:Loopback,0 ) 
this is the log out:

2023-12-15 11:36:15.912336 INFO  [src/bin.rs:683] CamillaDSP version 2.0.0
2023-12-15 11:36:15.912596 INFO  [src/bin.rs:684] Running on linux, arm
2023-12-15 11:36:16.079361 INFO  [src/alsadevice.rs:648] Capture device supports rate adjust
2023-12-15 11:36:16.118391 INFO  [src/alsadevice.rs:142] PB: Starting playback from Prepared state
2023-12-15 11:36:19.191169 WARN  [src/alsadevice.rs:281] Capture device failed while waiting for available frames, error: ALSA function 'snd_pcm_wait' failed with error 'EPIPE: Broken pipe'
2023-12-15 11:36:19.191409 ERROR [src/bin.rs:307] Capture error: ALSA function 'snd_pcm_wait' failed with error 'EPIPE: Broken pipe'

Work fine on 64bit os with the same .yml config file .

**Comment by HEnquist** [comment]
Can you please run this with trace log level and post the output, together with the full config file?

**Comment by melomane63** [comment]
[camilladsp.log](https://github.com/HEnquist/camilladsp/files/13689789/camilladsp.log)

[config files.tar.gz](https://github.com/HEnquist/camilladsp/files/13689840/config.files.tar.gz)

**Comment by HEnquist** [comment]
Thanks!
I see some of these lines:
`2023-12-15 21:57:30.597097 TRACE [src/alsadevice.rs:274] Capture waited for Some(39.145833ms), ready`
39 ms is about twice what it should be. It looks as if sometimes the event that signals that the loopback is ready goes missing. There have been similar issues before, and if I remember correctly it seemed linked to then the CPU governor adjusted the CPU frequency. Could you try locking the CPU frequency to a single value?

**Comment by melomane63** [comment]
Set governor on Performance
no luck

[camilladsp.log](https://github.com/HEnquist/camilladsp/files/13692639/camilladsp.log)

**Comment by HEnquist** [comment]
Ok, well it was worth a try. Thanks for testing!

**Comment by HEnquist** [comment]
Don't have any new clever ideas unfortunately. Does it work better with a 2x or 4x larger chunksize?

**Comment by melomane63** [comment]
Very quick tested, it seem work with 4096. Not the time now, i test in deep after tomorrow  Where is the différence under 32 and 64 bit ?


Le 19 décembre 2023 21:25:49 GMT+01:00, Henrik Enquist ***@***.***> a écrit :

**Comment by HEnquist** [comment]
Ok!
There shouldn't be any difference between how this behaves on 32 and 64-bit systems. But the kernel may be somewhat different, not sure how similar these versions are.

**Comment by HEnquist** [comment]
Does this still happen on the latest release?

**Comment by melomane63** [comment]
i don't know, i don't use anymore 32 bit version. sorry.

**Comment by HEnquist** [comment]
Ok no worries. Let's close this issue then.
