### ISSUE TITLE
Camilladsp 2.0.1 on Raspberry Pi OS (64-bit) Bookworm, cannot start

### ISSUE THREAD

**Issue by aci996** [HEnquist/camilladsp#316]
**Describe the bug**
Cannot start Camilladsp v2.0.1 on Raspberry Pi OS (64-bit) Bookworm.
Log says: 
2024-01-25 14:25:36.797300 ERROR [src/bin.rs:307] Capture error: ALSA function 'snd_pcm_open' failed with error 'EINVAL: Invalid argument'
2024-01-25 14:25:36.797487 ERROR [src/processing.rs:50] Message channel error: receiving on a closed channel

Tried with different devices, default and usb. Camilladsp v1 starts and works ok.

**To Reproduce**
1. fresh install of  Raspberry Pi OS (64-bit) Bookworm,
2. download Camilladsp 2.0.1
3. Try to start

**System info**
Raspberry Pi OS (64-bit) Bookworm
Raspberry Pi5 (Tried with 4 as well)
Camilladsp v2.0.1

**Configuration**
description: null
devices:
  adjust_period: null
  capture:
    channels: 2
    device: default
    format: S32LE
    type: Alsa
  capture_samplerate: 44100
  chunksize: 1024
  enable_rate_adjust: null
  playback:
    channels: 2
    device: default
    format: S32LE
    type: Alsa
  queuelimit: null
  rate_measure_interval: null
  resampler:
    profile: Balanced
    type: AsyncSinc
  samplerate: 96000
  silence_threshold: null
  silence_timeout: null
  stop_on_rate_change: null
  target_level: null
  volume_ramp_time: null
filters: {}
mixers: {}
pipeline: []
processors: {}
title: Mute

**Logs**
2024-01-25 14:25:36.797300 ERROR [src/bin.rs:307] Capture error: ALSA function 'snd_pcm_open' failed with error 'EINVAL: Invalid argument'
2024-01-25 14:25:36.797487 ERROR [src/processing.rs:50] Message channel error: receiving on a closed channel

**Comment by HEnquist** [comment]
Could you please repeat this with trace level logging, and attach the whole log?

**Comment by HEnquist** [comment]
Is this still a problem?
Others have reported that things are working well on bookworm.

**Comment by HEnquist** [comment]
Closing because of lacking information. Please reopen and provide complete logs if this still is a problem.
