### ISSUE TITLE
Error with DEBIAN 11: libc6

### ISSUE THREAD

**Issue by tarokeitaro** [HEnquist/camilladsp#317]
libc6 is installed by default on debian11. what do I have to do?

![image](https://github.com/HEnquist/camilladsp/assets/42670754/ec4d5b6c-3ae6-4f41-a360-29efd9d1e3b6)

**Comment by HEnquist** [comment]
The pre-built binaries are built on the default Ubuntu image provided by github. That tends to use newer versions of things like libc than Debian. To get it running on Debian 11, the easiest would be to just install the rust compiler and build from source. The Cargo tool makes this process quite smooth, see the "Building" section of the readme: https://github.com/HEnquist/camilladsp/blob/master/README.md#building

**Comment by HEnquist** [comment]
Closing as there is nothing more to do here. Please create a new issue if there are problems when following the readme to compile.
