### ISSUE TITLE
Configuration is not valid after update (moode audio)

### ISSUE THREAD

**Issue by PLTomO** [HEnquist/camilladsp#329]
Invalid config in CDSP file after moode audio update.

**To Reproduce**
1. Update Moode audio to newer version
2. Reboot
3. Try to play any sound
4. MPD error
5. Issue is caused by CDSP config error
✗ Configuration is not valid
Invalid config file!
devices: unknown field `enable_resampling`, expected one of `samplerate`, `chunksize`, `queuelimit`, `silence_threshold`, `silence_timeout`, `capture`, `playback`, `enable_rate_adjust`, `target_level`, `adjust_period`, `resampler`, `capture_samplerate`, `stop_on_rate_change`, `rate_measure_interval`, `volume_ramp_time` at line 14 column 3

**System info**
- operating system: Raspberry Pi 4
- cpu architecture ARM
- camilladsp version 2.0.1

**Configuration**
[Stereo_correction.txt](https://github.com/HEnquist/camilladsp/files/14392205/Stereo_correction.txt)

**Logs**
run camilladsp with debug logging (-v). If it's short, paste it directly here, otherwise attach it as a separate file.

**Comment by HEnquist** [comment]
This is expected since camilladsp V2 introduced some changes in the config format.
Just open the config file in a text editor and remove the offending field(s). Once it's loaded you can add back anything that's missing.

**Comment by HEnquist** [comment]
Ok, then it's a problem with your moode system. My best guess is that something went wrong during the update. I would suggest to try to wipe and do a fresh install of the latest version. If that doesn't help, then please ask in the moode forum at https://moodeaudio.org/forum/
