### ISSUE TITLE
Add a compressor filter

### ISSUE THREAD

**Issue by HEnquist** [HEnquist/camilladsp#33]
should process one waveform based on a control input from another channel

**Comment by nseyedtalebi** [comment]
An idea I got from an ad for a power amp: a compressor that is set based on driver Xmax. You'd need to have at least an estimate for the T-S parameters, but that is usually pretty easy to get. Not even sure if it's useful in practice, but I liked the idea and wanted to share in case it might be.

**Comment by HEnquist** [comment]
I have been thinking about something along those lines. I think that such a compressor should be smart and apply some frequency-dependent compression. It gets a bit involved, but certainly doable.

**Comment by HEnquist** [comment]
This won't be built the way I first intended, see https://github.com/HEnquist/camilladsp/issues/23

Instead I'll make something less generic and much simpler.

**Comment by Arnwald** [comment]
A limiter for speaker protection could also be great!

**Comment by HEnquist** [comment]
> A limiter for speaker protection could also be great!

This has been on my to-do list for quite some time. I'll add a limiter filter when I add the compressor. It already exists, as part of the compressor. I just need to break it out as a separate filter.

**Comment by Arnwald** [comment]
Great!
I have a potential business project that could involve CamillaDSP. How can we discuss about it?

**Comment by HEnquist** [comment]
Drop me an email (address is in my profile).
Short version is that I don't offer commercial licences because I simply don't have the time to handle it properly. But of course camilladsp can still be used in commercial projects, as long as the GPL terms are followed.

**Comment by HEnquist** [comment]
The compressor is done! It will be included in version 1.1. See https://github.com/HEnquist/camilladsp/tree/next11#compressor
There is also an example config for compressing only low frequencies here: https://github.com/HEnquist/camilladsp/blob/next11/exampleconfigs/lf_compressor.yml
