### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by spinwell** [HEnquist/camilladsp#34]
Hello,

first of all: this project is very interesting! I knew about it on diyaudio.com.

I tried to compile it on a volumio installation over a futro (a headless pc). Volumio is updated and i followed your guide for installation (pkg-config, alsa and pulseaudio dependecies) but after "cargo install --release" i've got:

`   Compiling libpulse-sys v1.12.1
error: failed to run custom build command for `libpulse-sys v1.12.1`

Caused by:
  process didn't exit successfully: `/home/volumio/Downloads/camilladsp/target/release/build/libpulse-sys-49ca079bb0973535/build-script-build` (exit code: 1)
--- stderr
`"pkg-config" "--libs" "--cflags" "libpulse" "libpulse >= 12.0"` did not exit successfully: exit code: 1
--- stderr
Requested 'libpulse >= 12.0' but version of libpulse is 5.0
`

I checked the version of libpulse and it is 5.0. I tried to update but it's the newest under Volumio.
Could you please help me? Thank you.

**Comment by HEnquist** [comment]
Hi!
For some reason it seems that many distributions ship with very old versions of pulseaudio. Do you need pulse, or would it be fine to run without? For a headless system I'm guessing you don't use pulse. So, just disable the default features (alsa and pulse) and then add back alsa:
cargo install --no-default-features --feature alsa-backend

The develop branch is currently quite far ahead of master, so you might want to go with that one instead.

**Comment by spinwell** [comment]
Clear, thank you!
