### ISSUE TITLE
Suggestion: Publish camilladsp to crates.io

### ISSUE THREAD

**Issue by ameknite** [HEnquist/camilladsp#350]
In the rust community is common to upload binaries to [crates.io](https://crates.io/) so it can be easier to install using:

```cargo install camilladsp```

or download the binaries from github using [`cargo binstall`](https://github.com/cargo-bins/cargo-binstall)

```cargo binstall camilladsp```

This will also make easier to update the program with [cargo-update](https://github.com/nabijaczleweli/cargo-update):

```cargo install-update camilladsp```

if you like the suggestion, I could help with the github workflow

**Comment by HEnquist** [comment]
I'm publishing a few libraries on crates.io, for example https://crates.io/crates/rubato

I have considered publishing also camilladsp on crares.io but what has kept me from doing it is that then all dependencies must be published there too. That is normally the case, but a few times I have used forks of some libraries to get a new camilladsp version out without having to wait for the updated library. Such a version could not be published to crates.io so the version there would lag behind.

**Comment by ameknite** [comment]
Oh, I didn't know about that. But if you want to keep the same versions in sync, I think you can actually publish the forks with a different name to crates.io, or even vendor the crates. But, I understand it can be annoying to keep updating the forks.

The easiest solution would be to just publish to crates.io and add a disclaimer in the readme that the version could be left behind. I think it is better to have that version than none at all, but it would be up to you.

**Comment by ameknite** [comment]
It looks like right now camilladsp is not using any external crates. So at least the current version can be published.

**Comment by HEnquist** [comment]
Another point is that I think crates.io is primarily used by rust developers, mostly to find libraries and occasionally some tools they need for some project. Would anyone go looking there for something like camilladsp?

I haven't tried but `cargo install` should also work without publishing to crates.io, with the `--git` option: https://doc.rust-lang.org/cargo/commands/cargo-install.html#synopsis

**Comment by ameknite** [comment]
Yeah, I just thought it was a nice to have, maybe something like homebrew might be better.

**Comment by HEnquist** [comment]
Yes homebrew is great. It would be neat if someone made and submitted a formula 😉
