### ISSUE TITLE
first contact

### ISSUE THREAD

**Issue by balbuze** [HEnquist/camilladsp#38]
hello!
I just saw your work and it seems promising!
I wrote a plugin using brutefir for Volumio [https://volumio.org/volumio-overview/](url)
My plugin : [https://github.com/balbuze/volumio-plugins/tree/master/plugins/audio_interface/brutefir3](url)
I'm going to give a try with Camilladsp now!

**Comment by HEnquist** [comment]
Nice! I'm not very familiar with Volumio, but I have been using brutefir for some time. If you have a working setup with BruteFIR you should be able to get CamillaDSP running easily.
Please let me know if you have any suggestions for improvements or changes in CamillaDSP!

**Comment by balbuze** [comment]
ok thank you! I have successfully tested it with my filter generated for brutefir, 65535 taps long. It needs more testing. With brutefir I implemented a "volume based filtering". This a sort of "loudness" that apply different filters according to volume level. I use the CLI of brutefir, it works on the fly, with no interruption while switching between filters. I also implemented an auto clipping detection to adjust level to avoid clipping with certain filters. It support up to 8 channels (2x4). I don't know yet what I'm going to do with CamilliaDSP but I 'm really interested by it!

**Comment by HEnquist** [comment]
How did you implement the filter switching?  By modifying BruteFIR? Or by measuring the level on the side somehow and just telling BruteFIR to switch?
If the -p parameter doesn't work it means you don't have the websocket server built in. That could be caused either by compiling an earlier version that doesn't have it, or by disabling it with the --no-default-features flag. Try updating and building again. Both 0.0.12 in master, and 0.0.13 in develop should be fine.

**Comment by HEnquist** [comment]
It's probably faster if we continues via email. My email is in Cargo.toml!
