### ISSUE TITLE
Is it possible to select specific capture/playback device channels?

### ISSUE THREAD

**Issue by Bilibilibill** [HEnquist/camilladsp#381]
Thank you for your excellent work on this project!

I have a question regarding the configuration of devices in the config files. It seems that currently, only the total number of `channels` can be specified. I was wondering if it might be possible to select specific channels based on particular needs.

For instance, using the BlackHole 64ch audio driver, what if I need to utilize only the first 10 channels and the last 10 channels while skipping the remaining 44 channels? Similarly, would it be feasible to configure usage for only the first few channels of two aggregated devices on macOS?

I would greatly appreciate any insights you can provide on whether this can be achieved or if there’s a workaround available. Thank you so much for your time and support!

**Comment by HEnquist** [comment]
Camilladsp always captures all the channels from the device, there is no way to pick and choose specific channels. You get around this by adding a mixer that drops the unwanted channels. When you add this mixer to the pipeline, then the capture side realizes that some channels are not being used, and it skips processing of these. So their raw data is still being read from the device, but then format conversion and resampling (if enabled) is skipped, and these channels are not passed  to the pipeline.
