### ISSUE TITLE
Feedback Path

### ISSUE THREAD

**Issue by MaxiMars73** [HEnquist/camilladsp#384]
Feedback routing
AuxOut(x) and AuxReturn(x) to achieve feedback, for example. Something like a free patch cable.

The background:
I am trying to recreate the following algorithm (RACE, Recursive Ambiophonic Crosstalk Elimination).
[
![](https://mathis-nitschke.com/wp18/wp-content/uploads/2020/04/ambiophonics-race-algorithm.png)
](url)

My problem is that there is no feedback path, as far as I know.

At the moment I am trying to achieve it with Blackhole, but this creates other problems.

It would be easy with an Aux-Out and an Aux-Return filter-step (module), which would work like a patch cable. You could create a connection from any point in the pipeline to any other point.

I imagine it would be relatively easy to implement this. Write the current value into a variable and read it out again at any another point in the pipeline.

**Comment by HEnquist** [comment]
Feedback like this isn't possible with how the CamillaDSP pipeline is designed. It always lets each filter process a full chunk before moving on to the next filter. This is good for efficiency, especially for FIR filters.
Doing RACE properly will require a specific RACE processor. That is something I'm planning to add some point, don't know when yet.

**Comment by MaxiMars73** [comment]
Thanks Henrik, learned: processing runs chunk wise not sample wise.

**Comment by HEnquist** [comment]
Replaced by #385
