### ISSUE TITLE
Add support for JACK

### ISSUE THREAD

**Issue by Artefact2** [HEnquist/camilladsp#72]
You can somewhat use camilladsp with JACK as it is, using alsa_in/alsa_out and a loopback ALSA device. However, there is a lot of back-and-forth and a lot of resampling going on, so this is not very good.

Having camilladsp more tightly integrated with JACK enables applications to measure the exact latency to physical hardware (which cannot be done with pure ALSA when a loopback is used), which is critical for accurate synchronisation of sound with other events (like graphics on a screen).

**Comment by HEnquist** [comment]
I have considered adding jack support, but since nobody asked about it (until now) I didn't do anything about it. There is a jack binding for rust that looks good: https://crates.io/crates/jack
I will add it to my todo-list it will probably be a while until I have tíme to start on it.

**Comment by larxxor** [comment]
This looks like a well defined coding task. Maybe solve by generalizing input. 
I'm wondering if I or someone else could do it. Jack connectivity opens up a lot of interesting possibilities.

**Comment by HEnquist** [comment]
I still have a pretty long list of things I want to get done before looking into jack. It would be helpful if someone else works on this, then it could be ready much faster.
I have never used jack, only read a little about how it works. Camilladsp runs capture and playback in separate threads. That likely means it will have to make two separate connections to jack. It's not yet clear to me if that is a problem or not.

**Comment by larxxor** [comment]
I know long todo lists very well ;) 

I will setup jackd daemon and start cracking at a solution.

**Comment by HEnquist** [comment]
It looks like maybe Pipewire will replace both PulseAudio and Jack. Because of that, I think it's best to wait and seen what happens with that before investing any time in Jack. Maybe there should be a pipewire backend instead?

**Comment by filmor** [comment]
You'd still use the JACK API for low latency audio with Pipewire. It's "replacing" pulse and jack by providing their interfaces.

**Comment by HEnquist** [comment]
Sure that is the case now. But for how long will that be the way to do it? If it really becomes the new standard, then at some point it makes much more sense to use the native pipewire interface instead of talking to it via two separate apis.

**Comment by Artefact2** [comment]
Nothing is standard in the linux audio stack. Pulseaudio has been around for a long time and its usage is still somewhat controversial. JACK has also been around for a long time and is well established in the "audio enthusiast" community, with a lot of tools and software that can talk to it. Its ABI is not going anywhere in the forseeable future.

If you wait for a standard to emerge, you'll be waiting a long time. The JACK API is simple, with well defined use cases. Since pipewire supports its ABI then you'll satisfy both JACK and pipewire users instead of forcing the former to use different software.

**Comment by filmor** [comment]
It also says clearly in the [Pipewire FAQ](https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/FAQ#what-audio-api-do-you-recommend-to-use):

> We recommend that you continue to use PulseAudio, JACK and ALSA API's for now.

I'll also take a shot at JACK support.

**Comment by HEnquist** [comment]
I have seen that, and it's the "for now" that bothers me. I don't have any time to work on either anytime soon so it doesn't matter much for me at the moment. 

If anyone makes a nice well working jack implementation I can include it. In that case I would like to be able to track the work in progress.

I mean "standard" = "what most of the common distros use as default"

**Comment by filmor** [comment]
Is there any particular reason why you only use CPAL for Windows and macOS right now?

**Comment by HEnquist** [comment]
> Is there any particular reason why you only use CPAL for Windows and macOS right now?

Yes, I did like that to evaluate CPAL, and to see how much interest there is for mac and windows. It turns out hat using CPAL abstracts away many important things that I really would need access to. My plan is actually to stop using CPAL for both of those. 

I didn't think about using cpal for jack, that's a good idea. Even with limitations it would still be much better than nothing

**Comment by HEnquist** [comment]
There is now a completely untested version with jack support via cpal  here: https://github.com/HEnquist/camilladsp/tree/jack

I have only checked that it compiles, no idea if it works yet.

**Comment by HEnquist** [comment]
Update on the above. It does seem to run.
I tried with "default" as devicename for both capture and playback devices, 48 kHz samplerate, and FLOAT32LE sample format.
I did not change any settings on the jack server, just started it with it's default settings (on Fedora if that matters).

**Comment by HEnquist** [comment]
I have never used Jack, so I'm a little lost when trying to test this. Could someone who actually knows what they are doing help with testing this? I would also appreciate some input on what to write here: https://github.com/HEnquist/camilladsp/blob/jack/README.md#jack

**Comment by HEnquist** [comment]
Did anyone have a chance to try this?
