### ISSUE TITLE
Add equal-loudness contour filter

### ISSUE THREAD

**Issue by Artefact2** [HEnquist/camilladsp#73]
Similar to [alsaloudness](https://github.com/dpapavas/alsaloudness), but done as a camiliadsp internal filter.

![](https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Lindos1.svg/800px-Lindos1.svg.png)

![](https://raw.githubusercontent.com/dpapavas/alsaloudness/master/filterplots.png)

Two parameters are required: the reference level (in phon) and the desired attenuation (or boost, if positive) in dB/LU. The actual EQ curve is the difference between the two contours.

**Comment by HEnquist** [comment]
Thanks, this is a nice idea. I will implement it, probably by fitting the curves with sets of biquads.

**Comment by JWahle** [comment]
There is a very simple, but very nice implementation of this in a dac manufactured by RME - the ADI 2 DAC FS.

This is how it works:
They implemented the low and high boost with a low shelf and a high shelf filter.
The loudness compensation is fixed to a window of 20dB.
So they have 3 parameters: the low_volume_reference, high-gain and low-gain.
If the volume is <= low_volume_reference, the gain of the filters is simply high-gain and low-gain.
If the volume is >= low_volume_reference, the gain of both filters is zero.
If the volume is < (20dB + low_volume_reference) and > low_volume_reference, then the filter gain is scaled linearly:
`gain = (volume - low_volume_reference) / 20`

e.g.:
5dB above low_volume_reference => 3/4 gain
10dB above low_volume_refernce => 1/2 gain
etc...

The end user simply sets the low_volume_reference to the lowest listening volume that they would use,
alternates between low_volume_reference and 20dB higher volume
and adjusts the low/high-gains, until there is little perceived change in sound signature between the volumes.

I find this easy to set up and for me, the sound improvement was dramatic - I miss loudness compensation whenever I don't have it.
The manual ([adi2dac_manual.pdf](https://github.com/HEnquist/camilladsp/files/5759493/adi2dacr_e.pdf)) describes this and the motivation behind it (page 14 and 23) and on page 57 are example frequency response curves.

**Comment by HEnquist** [comment]
Thanks, this is great! I have been experimenting with fitting a set of Peaking filters to the contours but haven't had much success. This is very nice solution, and much simpler to implement.

**Comment by HEnquist** [comment]
This is now implemented inthe develop branch. https://github.com/HEnquist/camilladsp/blob/develop/README.md#loudness

Please take a look!

**Comment by HEnquist** [comment]
Question: Currently the implementation is done just as in the RME dac. This means the compensation is scaled over a range of 20 dB, and the filters are placed at 70 and 3500 Hz. It would be easy to make these parameters adjustable, but on the other hand lots of parameters can be confusing. Opinions?
![loudness](https://user-images.githubusercontent.com/6504678/105228896-6f2c5b80-5b63-11eb-8af7-207b9974f3ce.png)

**Comment by JWahle** [comment]
Very cool, I'll have a look this weekend.

> It would be easy to make these parameters adjustable, but on the other hand lots of parameters can be confusing. Opinions?

The RME ADI 2 DAC only offers reference level and high/low gain - nothing else.
So I don't know yet, how much value additional parameters bring.
If you want to offer more options, I think they should be optional with good defaults.

I'd like to play with the filter slope. What value do I need to use for biquad shelves to get the same filter you used?

**Comment by HEnquist** [comment]
The filters I use now are configured like this:
```
high:
    type: Highshelf
    freq: 3500.0,
    slope: 12.0,
    gain: relative_boost * high_boost

low:
    type: Lowshelf
    freq: 70.0,
    slope: 12.0,
    gain: relative_boost * low_boost
```
This matches the RME curves closely. "relative_boost" is a value between 0 and 1.

**Comment by JWahle** [comment]
This sounds really nice - to me this is indistinguishable from the RME.
All parameters work as expected.

I tried to model the -20dB curve from Artefact2 by tweaking the shelf parameters, but it didn't sound as good.
If you want to try it yourself, [here is the config](https://github.com/HEnquist/camilladsp/files/5859088/loudness-filters-iso.zip).

After fiddling with the parameters, I would advise to keep it simple and NOT expose any additional parameters.
high_boost and low_boost are by far the most important filter parameters.

Is it possible to get the volume from the audio device instead of using CamillaDSPs internal volume for loudness correction (or at least provide that as an option)?

**Comment by HEnquist** [comment]
Then it seems like RME did their homework well. I'll leave it like it is then.
Reading the volume from the audio device could be nice, I'll put it in the queue of things to consider.

**Comment by JWahle** [comment]
Cool, I think that would make it much more useful in real world scenarios.

Do you think, there is a benefit to implementing loudness and volume as filters?
I just thought, that it would be simpler to set up, if you just add one mixer to the pipeline, instead of having to configure it for each channel separately.
This loudness/volume mixer would automatically have the right number of inputs/outputs and apply to all channels.

**Comment by HEnquist** [comment]
The benefit of having them as filters is that you can choose to have volume control for only some channels. For example in a 2-way active crossover, you can have volume control on the four channels going to the speakers, and send unfiltered signal at fixed level on two channels (to a TV or something with it's own volume control). 
The downside is of course that you need to add the volume control to every channel.

**Comment by JWahle** [comment]
I think, this issue can be closed now.
