### ISSUE TITLE
Add LV2/LADSPA/VST filters

### ISSUE THREAD

**Issue by Artefact2** [HEnquist/camilladsp#74]
Allow loading arbitrary LV2, LPDSPA (or VST, but the API is proprietary to my understanding) modules as camiliadsp filters.

**Comment by HEnquist** [comment]
For LV2 and LADSPA the available rust bindings only allow making plugins, and not hosts. So adding support for these plugins also means the bindings have to be developed which will be very time consuming. I'll have to postpone this until there are stable bindings that supports hosting plugins as well.

For  VST there is a binding, which woud work with plugins that do not have a gui. I'm not familiar with VST plugins, but I get the impression they are usually controlled using a gui so this might not be very useful(?).

**Comment by HEnquist** [comment]
I have looked a bit at this, and have come to the conclusion that I will not implement it.
