### ISSUE TITLE
Make --check suitable for consumption by scripts

### ISSUE THREAD

**Issue by JWahle** [HEnquist/camilladsp#78]
I would like to integrate a config check into the UI of a web app (Webinterface of Moode Audio).
For that it would be nice, if the output of CamillaDSPs `--check` command would be nicer.

Running `camilladsp -c invalid.yml` results in return code 0 (indicating everything went fine) and the output:
```
2020-12-06 02:49:19.486 ERROR camilladsp - Invalid config file!
while parsing a block mapping, did not find expected key at line 3 column 3
```

What I would like to see is return code >0 and output:
```
Invalid config file!
while parsing a block mapping, did not find expected key at line 3 column 3
```

**Comment by HEnquist** [comment]
This is a good idea and also quite easy to implement. I'll include in the next version!

**Comment by HEnquist** [comment]
I have updated the develop branch, please take a look!

**Comment by JWahle** [comment]
Looks good, thanks for implementing this so quickly :+1:
