### ISSUE TITLE
Stronger version of --check that includes filter files

### ISSUE THREAD

**Issue by JWahle** [HEnquist/camilladsp#80]
In order to catch as many errors as possible while creating the config and to prevent debugging (possibly on a remote machine) as much as possible,
I would like to have a stronger version of `--check` that also checks that:
- filter files exist
- filter files are readable (have correct format, skip_bytes_lines and read_bytes_lines)

The old `--check` should probably stay as it is, as just checking the config for syntax validity probably also has its use-cases.

**Comment by HEnquist** [comment]
This check is already included! For any filter that has a coefficient file, the coefficients are read from the file as part of the check.

**Comment by JWahle** [comment]
Oh, you're right.
I experimented a little to see which errors are reported and which are not.
Apparently, only elements which are included in the pipeline are checked - this got me fooled.
Once I included the filter in the pipeline, I got an error. So everything is fine here :+1:
