### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by jonach66** [HEnquist/camilladsp#82]
Hi Henrik,

I´ve used version 0.0.14 for a while, now I gave a try to version 0.4, but I´ve got this message:

`camilladspNEW: /lib/x86_64-linux-gnu/libm.so.6: version 'GLIBC_2.29' not found (required by camilladspNEW)`

It´s a linux thing, I know... any easy fix in mind?

Thank you in advance & kind regards!
Jo

**Comment by HEnquist** [comment]
Hi! Did you get the precompiled binary for 0.4.0? This is built on Ubuntu 19.10, I'm guessing that you have an older glibc than 2.29. What system are you running? You can probably just recompile it on your system to get around this. If it then complains about PulseAudio being too old try building without that (unless you need it of course).

**Comment by jonach66** [comment]
Hi Henrik!

Using Deb Buster and the precompiled version, only ALSA is required. So I will try to compile by myself.

Thank you for your prompt answer!

Jo

**Comment by HEnquist** [comment]
Did it work to recompile? If yes, can you close the issue?

**Comment by jonach66** [comment]
Sorry, not done yet, will try coming weekend!
Jo

**Comment by jonach66** [comment]
Hi Henrik,

recompile done on Debian Buster 4.19.0-8-amd64 after updating rust, just 2 warnings, but camillaDSP 0.4.0 is running nicely!

```
warning: use of deprecated associated function `alsa::PCM::io`: renamed to io_bytes
   --> src/alsadevice.rs:517:44
    |
517 |                         let io = pcmdevice.io();
    |                                            ^^
    |
    = note: `#[warn(deprecated)]` on by default

warning: use of deprecated associated function `alsa::PCM::io`: renamed to io_bytes
   --> src/alsadevice.rs:617:44
    |
617 |                         let io = pcmdevice.io();
    |                                            ^^

warning: 2 warnings emitted

    Finished release [optimized] target(s) in 0.11s
```

Kind regards!
Josef

**Comment by HEnquist** [comment]
Great! Thanks :)
