### ISSUE TITLE
Additional Documentation for chunk_size

### ISSUE THREAD

**Issue by JWahle** [HEnquist/camilladsp#86]
Hi Henrik,

on my RPI 3B when using sampling rates above 48kHz, there were frequent stutters due to buffer underruns.
It took me a while to realize that with each doubling of the sampling rate, I also had to double the chunk_size to get steady playback.
At least with ALSA output devices, the chunk_size seems to directly correlate with the sound card output buffer - I assume this is true for all hardware output devices.

I thought, you might want to include this information in the documentation to save some people the trouble - and maybe also yourself having to help them troubleshoot.

**Comment by HEnquist** [comment]
Hi! That's a good idea. I'll include more about this in the readme and add something in the upcoming faq as well. And I'll keep this issue open as a reminder until I have done it. 
Happy new year :)

**Comment by JWahle** [comment]
Happy new year!

That sounds good.

I gave this some further thought. Since increasing the chunk_size too heavily increases the output latency, simply increasing it, may not be desirable. Maybe it would be optimal, if the chunk_size scaled automatically with the sampling rate:
If the config has samplingrate: 44100 and chunk_size: 1024,
then if the samplingrate is overridden via command line to 88200, the chunk_size should automatically set to 2048.
The computation for the scaled chunk_size would look something like this:
`scaled_chunk_size = round(overridden_samplingrate / samplingrate) * chunk_size`

As a workaround, one could simply upsample all material to the highest sampling rate source material and the latency should be fine for all sources. Sound wise there should not be much noticeable difference - if any.

What do you think?

**Comment by HEnquist** [comment]
Yes it makes sense to scale both the chunksize and target_level when overriding the sample rate. I'll include that in the next release.

**Comment by JWahle** [comment]
Very nice!

Shouldn't `extra_samples` of File/Stdin inputs also scale?

**Comment by HEnquist** [comment]
extra_samples is already scaled!

**Comment by HEnquist** [comment]
This is now included in the current develop branch.

**Comment by JWahle** [comment]
I just tested this and it works nicely, if resampling is disabled.
With internal CamillaDSP resampling, the buffer is decreased by the resampling ratio.
My `chunk_size` is 1024 and capture_samplerate is 44100.
I get the following buffer sizes per samplerate:
samplerate | buffer_size
----|----
44100 | 1024
88200 | 512
176400 | 256

**Comment by HEnquist** [comment]
You mean the Alsa buffer size of the capture device? Can you describe what you did to get those numbers?
Is this correct?
config has:
enable_resamling = true
capture_samplerate = 44100
samplerate = ?
chunksize = 1024

Then you start with the samplerate override like --samplerate 88200?

**Comment by HEnquist** [comment]
Ah now I think I understood (and fixed) the problem. Can you try the updated version in develop?

**Comment by JWahle** [comment]
I should have mentioned, that I was talking about ALSA buffers and also be more clear about what's the sampling rate of source material vs. sample rate in the config :)
Now I get the correct buffer sizes - I think, you fixed it.
