### ISSUE TITLE
Enhancement: Systemd - CamillaDSP as a service

### ISSUE THREAD

**Issue by jonach66** [HEnquist/camilladsp#9]
Dear Henrik,

I´m a happy user of your CamillaDSP, running it on a 24/7 headless Debian / Intel system. 

For my usecase it would be greate to have a proper systemd init configuration, to start Camilla DSP as a service without any manual interference.

Any chance? Thank you in advance!
kr
jo

**Comment by jonach66** [comment]
Dear Henrik,

you did it already for Fedora, sorry, wasn´t aware!

kr
j

**Comment by HEnquist** [comment]
No problem :) Did you get the service to work?

**Comment by jonach66** [comment]
Worked like a charm on debian! Starting Camilla & Mopidy/Iris as a Service, smoothly!
Thank you!
