### ISSUE TITLE
Input validation for silence_threshold and silence_timeout

### ISSUE THREAD

**Issue by JWahle** [HEnquist/camilladsp#91]
I just noticed, that `silence_threshold` and `silence_timeout` are not validated.
This is not essential, but easy to fix.
AFAIK `silence_threshold` should be a number <= 0
and `silence_timeout ` should be a number >= 0

**Comment by HEnquist** [comment]
This is resolved by https://github.com/HEnquist/camilladsp/commit/8a72fcdbc251502bb193042662b682869b48b139

**Comment by JWahle** [comment]
I just tested this, works as expected.
