### ISSUE TITLE
Validation via Websocket differs from validation via command line

### ISSUE THREAD

**Issue by JWahle** [HEnquist/camilladsp#95]
It seems that validation via websocket is different from validation via command line.
The following config/coeff files are valid via command line but invalid when checked via the web interface (which uses the web socket for validation).
[broken-validation.txt](https://github.com/HEnquist/camilladsp/files/6018930/broken-validation.txt)
[Filter-44100-2.txt](https://github.com/HEnquist/camilladsp/files/6018928/Filter-44100-2.txt)

I think this config should also be valid via websocket.

**Comment by HEnquist** [comment]
I looked i to this and yes there is a mistake in the config handling that causes the validation via websocket to skip the substitution step. Will fix!

**Comment by HEnquist** [comment]
I pushed a fix for this to develop just now. Can you try it?

**Comment by JWahle** [comment]
Nice - works like a charm.
Adding a typo or changing the samplerate invalidates the cfg. Otherwise it is now valid.

**Comment by bitkeeper** [comment]
Great, also the samplerate works as expected. As well cmd line, online and offline.
Thanks !
