### ISSUE TITLE
SIGHUP terminates CDSP when in wait mode

### ISSUE THREAD

**Issue by JWahle** [HEnquist/camilladsp#96]
`sudo killall -s SIGHUP camilladsp` kills the CDSP process, when invoked as `camilladsp -p 1234 -w`.
When it is invoked via `camilladsp -p 1234 config.yml` it will keep running.

This is currently an issue in moOde, because the SIGHUP is sent to all CDSP processes when the config changes. Then the backup CDSP (for offline use) of camillagui-backend terminates.

This could also be fixed by having camillagui-backend restart the internal CDSP process, if it went down. However, I would prefer fixing it here.

**Comment by HEnquist** [comment]
I just pushed a fix for this to develop: https://github.com/HEnquist/camilladsp/commit/90f6c249275aa3a3f969ebaeed42c49c5da8ef54

Can you try it?

**Comment by bitkeeper** [comment]
Fix confirmed.

**Comment by JWahle** [comment]
I also just checked this and it works for me.
