### ISSUE TITLE
Problem with S24LE3 raw ir files

### ISSUE THREAD

**Issue by bitkeeper** [HEnquist/camilladsp#97]
When using a raw S24LE3 file as ir I get a strange distorted sound. It sounds a little bit the same as wrong selected format. The config has a gain filter infront of the fir filter to reduce the output.

Do you know if S24LE3 works correct ?

The raw file is based on wav with the following settings:
```
Input File     : 'test.wav'
Channels       : 1
Sample Rate    : 44100
Precision      : 24-bit
Duration       : 00:00:00.50 = 22050 samples = 37.5 CDDA sectors
File Size      : 66.2k
Bit Rate       : 1.06M
Sample Encoding: 24-bit Signed Integer PCM
```

I have create the raw (S24LE3) file with sox:
```
sox test.wav test_44100Hz_24b.raw ( or sox test.wav -b 24 test_44100Hz_24b.raw)
```

If I convert the 24bits file to 16 (S16LE)or 32(S32LE) bits everything sounds fine:
```
sox test.wav -b 16 test_44100Hz_16b.raw
sox test.wav -b 32 test_44100Hz_32b.raw
```

I have included the ir files in the attached zip:
[test_ir.zip](https://github.com/HEnquist/camilladsp/files/6064556/test_ir.zip)

**Comment by HEnquist** [comment]
I can confirm this, something goes wrong when reading 24-bit negative values. I'm on it.

**Comment by HEnquist** [comment]
Should be working on develop now! Can you check?

**Comment by bitkeeper** [comment]
I confirm that the fix works, thanks for the quick response!
