### ISSUE TITLE
6_L_32LE.raw'. Error: stream did not contain valid UTF-8

### ISSUE THREAD

**Issue by ynot123** [HEnquist/camilladsp#99]
Hello,

Was testing out your conversion method using both sox and audacity and keep getting the following error when trying to load the coeffs .raw file.  When I export as text in audacity the text files work fine.

`Invalid filter 'Convolver_L'. Reason: Can't read line 1 of file '/home/pi/camilladsp/coeffs/6_L_32LE.raw'. Error: stream did not contain valid UTF-8`

I have used both the current and develop versions with the same issue.,  I have included the .raw and text versions of the file as well for review if needed.

Thanks in advance, Yvon.  (CamillaDSP: 0.5.0;  pyCamillaDSP: 0.5.0;  Backend: 0.6.0; Debian Buster - PI3)
[Convolver_file.zip](https://github.com/HEnquist/camilladsp/files/6135924/Convolver_file.zip)

**Comment by HEnquist** [comment]
Hi,
It seems that you try to import a raw format coefficient file as text. You need to add a "format" parameter in the config, to tell camilladsp what format it's in. If you leave it out, it defaults to plain text. You probably want "format: S32LE".

**Comment by ynot123** [comment]
Thank you.  Was using the gui and changing the format there between TEXT and S32LE but apparently that parameter doesn't take when changing on the fly.  Appreciate the quick response.

**Comment by HEnquist** [comment]
Alright! There is a problem with the "format" parameter in the current gui release, it will be fixed in the next.

**Comment by ynot123** [comment]
Perfect.  Thanks.
